- Assets/Mirror/Runtime/Transport/Tcp/Client.cs
- Assets/Mirror/Runtime/Transport/Websocket/Client.cs
- Assets/Mirror/Runtime/Transport/Websocket/Server.cs
> Use Task instead of void

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
- Assets/Mirror/Components/NetworkProximityChecker.cs
- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Components/NetworkRoomPlayer.cs
- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/ZoneHandler.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
- Assets/Mirror/Examples/ListServer/ListServer.cs
- Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
- Assets/Mirror/Examples/Room/Scripts/Reward.cs
- Assets/Mirror/Examples/Room/Scripts/Spawner.cs
- Assets/Mirror/Examples/Tanks/Scripts/Projectile.cs
- Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkManagerHUD.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkStartPosition.cs
- Assets/Mirror/Runtime/NetworkTime.cs
- NetworkClient is now a component
- NetworkServer is now a component
- Remove NetworkManager singleton
> breaking: Remove NetworkClient and NetworkServer singletons

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Runtime/NetworkAuthenticator.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkDiagnostics.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkTime.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Mirror/Runtime/Transport/LLAPITransport.cs
- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
- Remove unused **using**.
- Remove blank lines.
- Fix code conventions
> Clean runtime code

- Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
- Assets/Mirror/Examples/Room/Scripts/Spawner.cs
- Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Network server knows about the host mode client, so
we don't have to pass it every time
this also improves compatibility with Mirror
> breaking: Simplify spawning

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
- Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
BREAKING CHANGE: AddPlayerForConnection no longer receives the client
> Simplify AddPlayerForConnection

- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
Also simplifies weaver code and add a new property to Networkbehaviour
> fix: calling syncvar hook when not connected yet

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Examples/ListServer/ListServer.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Play/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Play/NetworkManagerTest.cs
- Assets/Mirror/Tests/Play/NetworkServerTest.cs
- Assets/Mirror/Tests/Play/NetworkServerTests.cs
BREAKING CHANGE: now you set MaxConnections in the NetworkServer
> Move maxConnections to NetworkServer

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Play/RpcTests.cs
This functionality got removed when we moved Spawned to NetworkClient/NetworkServer.
This PR restores that functionality
> feat: Now you can pass NetworkIdentity and GameObjects

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Play/NetworkServerTest.cs
> Use event for connected

- Assets/Mirror/Runtime/NetworkAuthenticator.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
first baby step,  Move the authenticator field to NetworkClient and NetworkServer.
Logic will follow soon. 
BREAKING CHANGE: Authenticator field moved to NetworkClient and NetworkServer
> Authenticator

- Assets/Mirror/Components/NetworkSceneChecker.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/RandomColor.cs
- Assets/Mirror/Examples/Basic/Scripts/Player.cs
- Assets/Mirror/Examples/Pong/Scripts/Ball.cs
- Assets/Mirror/Examples/Room/Scripts/NetworkRoomPlayerExt.cs
- Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Room/Scripts/RandomColor.cs
- Assets/Mirror/Examples/Room/Scripts/Spawner.cs
- Assets/Mirror/Examples/Tanks/Scripts/Projectile.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Play/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Play/NetworkServerTest.cs
WIP PR do not merge. Trying to figure out tests and other misc issues.
> NetEdentityEvents WIP

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Tests/Play/HostTests.cs
Connect handler is being register twice in host mode
> fix: calling Connect and Authenticate handler twice

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Tests/Play/ClientServerTests.cs
- Assets/Mirror/Tests/Play/FlagsTests.cs
- Assets/Mirror/Tests/Play/HostTests.cs
Initialize is being called many times.  This is a problem for handlers pr
> Initialize NM only once during Start

- Assets/Mirror/Runtime/Transport/AsyncTcp.meta
- Assets/Mirror/Runtime/Transport/AsyncTcp/AsyncTcpTransport.cs
- Assets/Mirror/Runtime/Transport/AsyncTcp/AsyncTcpTransport.cs.meta
- Assets/Mirror/Runtime/Transport/AsyncTcp/TcpConnection.cs
- Assets/Mirror/Runtime/Transport/AsyncTcp/TcpConnection.cs.meta
- Assets/Mirror/Runtime/Transport/AsyncTransport.cs
- Assets/Mirror/Runtime/Transport/AsyncTransport.cs.meta
- Assets/Mirror/Runtime/Transport/IConnection.cs
- Assets/Mirror/Runtime/Transport/IConnection.cs.meta
- Assets/Mirror/Tests/Editor/Transport/AsyncTcpTransportTests.cs
- Assets/Mirror/Tests/Editor/Transport/AsyncTcpTransportTests.cs.meta
This will be the new transport API that gets rid of connectionId
> feat: next gen async transport

- Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkManagerTest.cs
Needs testing with scene change
Also, I'm pretty sure rooms example cannot work anymore.
Fixes #116
> refactor: Remove offline/online scenes

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/NetworkConnectionToServer.cs
> fix: client being disconnected twice

- Assets/Mirror/Runtime/NetworkClient.cs
> fix: client disconnected on server event never raised

- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
I named the branch wrong locally and cant seem to get it changed on the repo. This is not an event/virtual. Sorry for the typo.
> Remove on disconnect all

- Assets/Mirror/Runtime/Transport/PipeConnection.cs
- Assets/Mirror/Runtime/Transport/PipeConnection.cs.meta
- Assets/Mirror/Tests/Editor/PipeConnectionTest.cs
- Assets/Mirror/Tests/Editor/PipeConnectionTest.cs.meta
Creates a pair of connections that are linked to each other.  If you send data on one of them, the other one gets it.  They are awaitable.
These will be used for local connections in the async tranport branch.
> Piped connection

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
- Assets/Mirror/Components/NetworkProximityChecker.cs
- Assets/Mirror/Components/NetworkSceneChecker.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/ShootingTankBehaviour.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
- Assets/Mirror/Examples/ListServer/ListServers.cs
- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/LogFilter.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/PlayerSpawner.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Mirror/Runtime/Transport/Websocket/Client.cs
- Assets/Mirror/Runtime/Transport/Websocket/Server.cs
- Assets/Mirror/Tests/Runtime/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Runtime/NetworkManagerTest.cs
- Assets/Mirror/Tests/Runtime/RpcTests.cs
this wraps up the last of the easy ones. same as before all testing done locally before pushing.
> Misc code smells

- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Components/NetworkProximityChecker.cs
- Assets/Mirror/Components/NetworkSceneChecker.cs
- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Editor/NetworkScenePostProcess.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Runtime/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Runtime/NetworkIdentityTestsMirror.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTests.cs
compiles. passes all tests locally. examples work.
> NetworkIdentity code smells

- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Tests/Runtime/RpcTests.cs
fixes build errors with il2cpp
> fix: pass the correct connection to TargetRpcs

- Assets/Mirror/Runtime/INetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
Since we have the PipedConnection this is not needed anymore
> Remove unused InvokeHandler method

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkManagerTest.cs
make sure to properly cleanup and call events when we disconnect for any reason.
> fix: disconnect even if there is an exception

- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
don't LogError,  throw exception instead
> Simplify get network identity

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
- Assets/Mirror/Runtime/INetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/PlayerSpawner.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTests.cs
BREAKING CHANGE:  NetworkConneciton.RegisterHandler only needs message class
> Simplify RegisterHandler

- Assets/Mirror/Authenticators/Mirror.Authenticators.asmdef
- Assets/Mirror/Authenticators/Mirror.Authenticators.asmdef.meta
- Assets/Mirror/Tests/Runtime/Mirror.Tests.Runtime.asmdef
This was removed sometime in the past. Would like to add it back for Authenticator testing
> Add Mirror.Authenticators asmdef back

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
thought i pushed this yesterday
> Net identity tests

- Assets/Mirror/Runtime/NetworkManagerHUD.cs
tested and it functions the same as before
> smell: reduce complexity of OnGUI

- Assets/Mirror/Editor/NetworkClientInspector.cs
- Assets/Mirror/Editor/NetworkClientInspector.cs.meta
- Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
- Assets/Mirror/Tests/Editor/NetworkClientInspectorTest.cs
- Assets/Mirror/Tests/Editor/NetworkClientInspectorTest.cs.meta
A button to populate the list of prefabs in NetworkClient
> feat: Button to register all prefabs in NetworkClient

- Assets/Mirror/Runtime/NetworkClient.cs
Already set in:
ClientMode: NetworkClient.cs:121
HostMode: NetworkClient.cs:148
All tests passed locally. Examples tested.
> Dont set existing connection

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
rewrite of previous PR to fix merge issues weirdness.
> move last of NetMan virtuals to NS

- Assets/Mirror/Runtime/NetworkManager.cs
this was removed from NG and no longer applies
> fix: remove pause network comment and log

- Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Main.unity
> fix: MultipleAdditiveScenes example errors

- Assets/Mirror/Cloud/Core/Logger.cs
- Assets/Mirror/Cloud/ListServer/ListServerClientApi.cs
- Assets/Mirror/Cloud/ListServer/ListServerServerApi.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
- Assets/Mirror/Components/Experimental/NetworkTransform.cs
- Assets/Mirror/Components/Experimental/NetworkTransformBase.cs
- Assets/Mirror/Components/Experimental/NetworkTransformChild.cs
- Assets/Mirror/Components/NetworkMatchChecker.cs
- Assets/Mirror/Examples/Benchmarks/10klight/Scripts/BenchmarkNetworkManager.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
- Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
- Assets/Mirror/Examples/Tanks/Scripts/TankGameManager.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Runtime/INetworkServer.cs
- Assets/Mirror/Runtime/Logging/NetworkHeadlessLogger.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/Transport/AsyncQueue.cs
- Assets/Mirror/Tests/Common/LoopbackTransport.cs
- Assets/Mirror/Tests/Editor/NetworkMatchCheckerTest.cs
- Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformanceLight.cs
- Assets/Mirror/Tests/Runtime/FlagsTests.cs
No real logic changes except for condensing a few things.
> fix: Misc Code Smells

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Tests/Runtime/NetworkSceneManagerTests.cs
Instead provide a custom NetworkSceneManager or replace the message handlers as needed.
> fix: remove customHandling as its no longer used

- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
All the Inject*Guard methods are the same except for a couple of values.
So just consolidate and pass the values as parameters
> Deduplicate Inject guard code

- Assets/Mirror/Runtime/NetworkSceneManager.cs
also provides support to the server to additive load scenes
> feat: Server and Client share the same scene loading method

- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Tests/Runtime/NetworkSceneManagerTests.cs
Is changing a public properties casing a breaking change?
> fix: dont directly set NetworkSceneName

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
> fix: NS call SpawnObjects. No NetMan dependency for spawning objects

- Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
As promised the file was refactored to use a standard setup/teardown and add the tests that led to #317
> NetworkIdentityTests refactor

- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Tests/Runtime/NetworkSceneManagerTests.cs
remove existing code smell for complexity.
> IsConnected is the same check as Active

- Assets/Mirror/Runtime/NetworkClient.cs
related to fixing one of the possible many bugs with: #235
> fix: add NRE short circuit for scene change

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Tests/Runtime/NetworkSceneManagerTests.cs
> fix: scene change race condition. wait for server to be ready

- Assets/Mirror/Components/NetworkPingDisplay.cs
- Assets/Mirror/Samples~/Common/NetworkPingDisplayPrefab.prefab
- Assets/Mirror/Samples~/Common/NetworkPingDisplayPrefab.prefab.meta
similar change to what was done with NetworkManagerHud moving to Canvas from legacy OnGUI
> new NetworkPingDisplay replaces OnGUI version

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/NetworkClientTest.cs
- Assets/Tests/Runtime/NetworkServerTests.cs
override the virtual method to pass in your own INetworkConnection.
> feat: Add support for customer INetworkConnections

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/ClientObjectManager.cs.meta
- Assets/Mirror/Runtime/INetworkClient.cs
- Assets/Mirror/Runtime/INetworkServer.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs.meta
no functionality impact to existing code. each commit compiles on its own. future PR would include the actual cutting to existing code.
> feat: starting NetworkObjectManager

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
generate reader and writer functions for enums instead of downcasting to base type
> Add reader and writer functions for enums

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Tests/Runtime/ClientServerComponentTests.cs
- Assets/Tests/Runtime/NetworkClientTest.cs
https://github.com/MirrorNG/MirrorNG/issues/368
Happens in Host and ClientServer
> bug: Client ConnectionState not set properly in Disconnect

- Assets/Mirror/Runtime/NetworkBehaviour.cs
> fix: access NI on disabled objects

- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Runtime/INetworkServer.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/NetworkSceneManagerTests.cs
Only removes small pieces that have no real breaking changes aside from the event that likely no one was using.
> Remove IsReady - Part 1

- Assets/Mirror/Editor/NetworkMenu.cs
- Assets/Tests/Editor/NetworkMenuTest.cs
KCP transport is a better default than TCP trasport
> perf: Make KCP the default transport

- Assets/Mirror/Runtime/Transport/Kcp/Kcp.cs
Just moving code. No functional changes (at least none intended!)
> Move code out of Flush to reduce complexity and work towards SRP

- Assets/Mirror/Runtime/INetworkClient.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/ClientServerComponentTests.cs
- Assets/Tests/Runtime/NetworkClientTest.cs
BREAKING CHANGE: GetPrefab now just returns the prefab or null
> Remove out parameter

- Assets/Mirror/Runtime/Transport/Kcp/Decoder.cs
- Assets/Mirror/Runtime/Transport/Kcp/Decoder.cs.meta
- Assets/Mirror/Runtime/Transport/Kcp/Encoder.cs
- Assets/Mirror/Runtime/Transport/Kcp/Encoder.cs.meta
- Assets/Mirror/Runtime/Transport/Kcp/HashCash.cs
- Assets/Mirror/Runtime/Transport/Kcp/Kcp.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
- Assets/Mirror/Runtime/Transport/Kcp/Segment.cs
- Assets/Mirror/Runtime/Transport/Kcp/Utils.cs
- Assets/Tests/Runtime/Transport/HashcashTest.cs
refactor encoding and decoding functions into structs.  Much more readable
> Modularize KCP encoder and decoder

- Assets/Mirror/Runtime/Transport/Kcp/ByteBuffer.cs
- Assets/Mirror/Runtime/Transport/Kcp/Kcp.cs
- Assets/Mirror/Runtime/Transport/Kcp/Segment.cs
- Assets/Tests/Editor/Transport/KcpByteBufferTests.cs
- Assets/Tests/Performance/Editor/KcpEditorPerformance.cs
```
10k WriteBytes
BEFORE:
Time Microsecond Median:248,90 Min:225,90 Max:3765,10 Avg:344,57 Std:392,16 SampleCount: 1000 Sum: 344572,10
AFTER:
Time Microsecond Median:211,40 Min:201,40 Max:4515,30 Avg:311,77 Std:437,20 SampleCount: 1000 Sum: 311767,50
```
> refactor: simplify ByteBuffer

- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Unitask cannot await multiple times.
reimplement accept in multiplex transport to avoid the problem.
fixes #413
> fix: Multiplex transport exception

- Assets/Mirror/Components/LobbyReady.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Runtime/INetworkClient.cs
- Assets/Mirror/Runtime/INetworkConnection.cs
- Assets/Mirror/Runtime/INetworkServer.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/IConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpClientConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpServerConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
- Assets/Mirror/Runtime/Transport/PipeConnection.cs
- Assets/Mirror/Runtime/Transport/Tcp/TcpConnection.cs
- Assets/Mirror/Runtime/UNetwork.cs
- Assets/Tests/Common/LoopbackTransport.cs
- Assets/Tests/Common/MockTransport.cs
- Assets/Tests/Editor/CustomAttrributeTest.cs
- Assets/Tests/Editor/NetworkDiagnosticsTests.cs
- Assets/Tests/Editor/PipeConnectionTest.cs
- Assets/Tests/Runtime/LobbyReadyTest.cs
- Assets/Tests/Runtime/Transport/KcpTransportTest.cs
- Assets/Tests/Runtime/Transport/TransportTests.cs
now you can specify a channel to use when you send something in a transport
> Transport api can now send messages in channels

- Assets/Mirror/Runtime/NetworkSceneManager.cs
confirmed with local testing and with dragon that it resolved his scene loading issue. for good this time?
> fix: third try to prevent double load

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Tests/Runtime/NetworkIdentityTests.cs
made a test and confirmed as fix related to #452
> fix: client NRE for objects spawned in .Started in hostmode 

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/RemoteCallHelper.cs
KISS,  no need to check null all over the place.
just throw an exception if we get a call for an invalid RPC.
> feat: throw exception if invalid rpc

- Assets/Mirror/Runtime/INetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
I think dragon called this one out,  after careful inspection,
it is not doing anything
> Simplify sending to multiple connections.

- Assets/Mirror/Runtime/NetworkBehaviour.cs
There is no valid use case for these methods to exist
> Remove public invokerpc methods

- Assets/Mirror/Editor/Mirror.Editor.asmdef
- Assets/Mirror/Editor/Weaver/Mirror.Weaver.asmdef
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ServerRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/RemoteCallHelper.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Tests/Editor/Weaver/WeaverNetworkBehaviourTests.cs
- Assets/Tests/Editor/Weaver/WeaverServerRpcTests.cs
- Assets/Tests/Editor/Weaver/WeaverServerRpcTests~/ServerRpcWithReturn.cs
- Assets/Tests/Runtime/ClientServerComponentTests.cs
- Assets/Tests/Runtime/MockComponent.cs
Allow returning values from [ServerRpc]
for example:
```cs
public class Shop: NetworkBehavior {
[ServerRpc]
public UniTask<int> GetPrice(string item) 
{
switch (item) 
{
case "turnip":
return 10;
case "apple":
return 8;
default:
return int.MaxValue;
}
}
[Client]
public async UniTaskVoid DisplayTurnipPrice() 
{
int price = await GetPrice("turnip");
Debug.Log($"Turnips price {price}");
}
}
```
> feat: return values from [ServerRpc]

- .github/workflows/docs.yml
should fix "improve this doc" links, hopefully.
> Update docfx plugin

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/INetworkClient.cs
- Assets/Tests/Runtime/ClientObjectManagerTest.cs
- Assets/Tests/Runtime/ClientServerComponentTests.cs
One spawn handler delegate is enough
BREAKING CHANGE: Removed redundant spawn handler
> Remove redundant spawn handler

- .releaserc.yml
yaml syntax is easier to read and supports comments
> use yaml syntax for release config

- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/NetworkSceneManagerTests.cs
Provides a test and fix for bug related to: #503
> bug: ServerSceneChanged fires twice on start

- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/HostSetup.cs
- Assets/Tests/Runtime/ServerObjectManagerTest.cs
> fix: network objects not destroyed on server stop

- .github/workflows/pr-name.yml
- commitlint.config.js
make sure that pr names follow conventional-commits
see https://www.conventionalcommits.org/en/v1.0.0/
> ci: validate PR names

- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/Host/ServerObjectManagerTest.cs
Fixes bug (#517) introduced in #468.
> fix: don't destroy network scene objects on server stop

- Assets/Mirror/Samples~/AdditiveScenes/Scenes/MainScene.unity
- Assets/Mirror/Samples~/MultipleAdditiveScenes/Scenes/Main.unity
fixes #522. First commit fixes the NRE in the screenshot but there are other issues remaining.
> fix: additive scene example not working

- Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
> fix: simplified SetHostVisibilityExceptionNetworkBehaviour test

- doc/Articles/Guides/Communications/RemoteActions.md
> docs: typo in RemoteActions doc

- .github/workflows/pr-name.yml
no need to checkout the entire history for checking the name of the PR
> ci: faster pr name check

- Assets/Mirror/Weaver/MirrorILPostProcessor.cs
Basically reverts PR #537
It did not solve the problem we intended to solve,
and it broke some code for someone.
fixes #552
> fix: running weaver for editor scripts

- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scenes/Scene.unity
- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/AdjustableLoad.cs
- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/HeadlessBenchmark.cs
currently getting: "Invalid message System.InvalidOperationException: There is already a player for this connection" after start. WIP until I figure out why. If you want to test it as is it seems to work with that exception on PlayerSpawner.cs:93 commented out.
> fix: better benchmark

- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
> feat: spawn an object by network identity ref

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Mirror/Samples~/Basic/Scenes/Example.unity
- Assets/Tests/Common/Castle.Core.dll.meta
- Assets/Tests/Common/NSubstitute.dll.meta
- Assets/Tests/Common/System.Threading.Tasks.Extensions.dll.meta
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
ClientObjectManager and ServerObjectManager now have events
that will be invoked when they spawn and unspawn objects.
> feat: raise event when spawning objects

- Assets/Mirror/Editor/WelcomeWindow/Resources/WelcomeWindow.uss
- Assets/Mirror/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirror/Editor/WelcomeWindow/WelcomeWindow.cs
Updated UI and added function to open to change log if the user downloaded a new version.
> feat: open changelog page when user downloaded a new version

- README.md
This is a pretty simple PR. It updates the Discord link to point to the Mirage Discord.
> doc: update discord link in README.md

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
Provides feedback to the user that tells them what tab they pressed/are in.
> feat: welcome window shows active tab

- Assets/Mirage/Runtime/INetworkSceneManager.cs
- Assets/Mirage/Runtime/NetworkClient.cs
> fix: add summaries to event classes

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uss
- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
#593 will also need ``screenToOpenKey``
> fix: tab button not tinted on welcome window start up

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uss
- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
A couple of issues with the welcome window's layout.
1. Redirect button is not at the bottom
2. Icon is a little bit squished vertically
3. Install buttons in ``Packages`` tab overlap
This PR should fix all these issues but there is no way to test unless its merged. Missing image will be fixed in #635 .
Images were taken when the window was launched on my game project.
> fix: welcome window layout

- .github/workflows/main.yml
speed up CI/CD by caching the library folder
> ci: cache the library folder

- doc/docfx.json
- doc/templates/unity/partials/head.tmpl.partial
- doc/templates/unity/styles/docfx.js
- doc/templates/unity/styles/main.css
UnityFX theme looks beautiful.
https://github.com/code-beans/UnityFX
> docs: switch to unityfx theme

- doc/Articles/Guides/MirrorMigration.md
- doc/Articles/Guides/toc.yml
Took the WIP guide from GitHub, rewrote it, added formatting, updated, added examples and some additional info.
> docs: added Mirror migration guide

- Assets/Mirage/Weaver/Processors/ReaderWriterProcessor.cs
just moving code...will merge since tests pass
> refactor(weaver): moving method is checks to their own functions

- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkConnection.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Weaver/Processors/ReaderWriterProcessor.cs
> refactor: making NetworkClient implement IMessageSender

- Assets/Mirage/Components/LobbyReady.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/NetworkPlayer.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Weaver/Processors/ReaderWriterProcessor.cs
BREAKING CHANGE: moving NetworkPlayer.Send to NetworkServer.SendToMany
> refactor: moving static send to NetworkServer

- Assets/Mirage/Runtime/NetworkPlayer.cs
- Assets/Mirage/Runtime/Sequencer.cs
- Assets/Tests/Editor/SequencerTest.cs
- Assets/Tests/Runtime/Serializers/NetworkConnectionTest.cs
the sequencer now returns 0 as the first value
> refactor: sequencer starts with 0

- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/NetworkServer.cs
BREAKING CHANGE: fields and parameters using NetworkServer are now using INetworkServer Instead
> refactor: using interface instead of network server

- Assets/Mirage/Runtime/INetworkSceneManager.cs
- Assets/Mirage/Runtime/NetworkSceneManager.cs
> refactor: event name should not be client specific

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/SyncVarReceiver.cs
- Assets/Mirage/Runtime/SyncVarReceiver.cs.meta
required: https://github.com/MirageNet/Mirage/pull/720
> refactor: moving syncvar recieve to its own class

- Assets/Mirage/Editor/NetworkMenu.cs
- Assets/Mirage/Runtime/NetworkManager.cs
> fix: better name to stop namespace conflict with Unity

- Assets/Mirage/Components/Experimental/NetworkLerpRigidbody.cs.meta
- Assets/Mirage/Components/Experimental/NetworkTransformBase.cs.meta
- Assets/Mirage/Components/HeadlessAutoStart.cs.meta
- Assets/Mirage/Components/HeadlessFrameLimiter.cs.meta
- Assets/Mirage/Components/LobbyReady.cs.meta
- Assets/Mirage/Components/ObjectReady.cs.meta
- Assets/Mirage/Components/OnlineOfflineScene.cs.meta
- Assets/Mirage/Runtime/CharacterSpawner.cs.meta
- Assets/Mirage/Runtime/ClientObjectManager.cs.meta
- Assets/Mirage/Runtime/NetworkAuthenticator.cs.meta
- Assets/Mirage/Runtime/NetworkBehaviour.cs.meta
- Assets/Mirage/Runtime/NetworkClient.cs.meta
- Assets/Mirage/Runtime/NetworkSceneManager.cs.meta
- Assets/Mirage/Runtime/NetworkServer.cs.meta
- Assets/Mirage/Runtime/ServerObjectManager.cs.meta
- Assets/Mirage/Runtime/Transport/Transport.cs.meta
CI isnt going to find anything with this PR. Any objections/comments before I merge?
> fix: add icons to all mirage monobehaviours

- Assets/Mirage/Runtime/NetworkManager.cs
- Assets/Tests/Runtime/Host/NetworkManagerTest.cs
resolves part of the issue for: #740
> feat: add NetworkManagerMode back to NetMan

- Assets/Mirage/Runtime/ClientObjectManager.cs
> fix: bug with scene object spawning

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uss
- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
feat: parse change log in welcome window.
> feat: welcome window displays what's new

- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
- Assets/Tests/Runtime/Host/ClientObjectManagerTest.cs
not needed on server side of object.
> refactor: remove client from replacecharacter

- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/Host/NetworkIdentityTests.cs
- Assets/Tests/Runtime/Host/ServerObjectManagerTest.cs
- doc/Articles/Guides/GameObjects/Lifecycle.md
- doc/Articles/Guides/MirrorMigration.md
> refactor: remove unspawn as its redundant with destroy

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
would like to do similar to client object manager if possible.
> refactor: identity assignment standardized

- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
> fix: server offline exception does not need a specific object

- Assets/Mirage/Runtime/ServerObjectManager.cs
even though 1 LOC is missing from tests. It is related to prefab spawning which already has poor test coverage. So I want to make sure that gets fixed before merge. Otherwise its ready for review.
> refactor: all spawn paths use this call simplify to one location

- Assets/Mirage/Runtime/NetworkServer.cs
removing set up function that call other set up functions
> refactor: simplifying server start flow

- Assets/Mirage/Runtime/NetworkClient.cs
requires: #821
This event can be useful to do things before connected. This along with message handler #818 will fix the host mode message issues.
Call order for hostMode
- Server.Start
- Client.Start
- Client.Connected and Client.Authenticated
- Server.Connected and Server.Authenticated
Call order of Connected vs Authenticated will be inconsistent because Authenticated is called by Connected so couldd be inbetween Connected event calls
> feat: adding started event to client

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Tests/Common/TestSocketFactory.cs
- Assets/Tests/Runtime/ClientServer/ClientServerSetup.cs
- Assets/Tests/Runtime/Host/HostSetup.cs
- Assets/Tests/Runtime/Host/NetworkServerMaxConnectionTests.cs
- Assets/Tests/Runtime/Host/NetworkServerMaxConnectionTests.cs.meta
- Assets/Tests/Runtime/Host/NetworkServerNoAutoStartTest.cs
- Assets/Tests/Runtime/Host/NetworkServerNoAutoStartTest.cs.meta
- Assets/Tests/Runtime/Host/NetworkServerTest.cs
- Assets/Tests/Runtime/NetworkIdentityCallbackTests.cs
new order:
- add player to server collection
- invoke client connected
- invoke server connected
> fix: fixing order of host setup

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/PipePeerConnection.cs
- Assets/Tests/Common/LocalConnections.cs
- Assets/Tests/Editor/PipePeerConnectionTest.cs
- Assets/Tests/Runtime/Host/HostComponentTests.cs
> fix: adding action to pipe connection so client events can be called on stop

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
fix: change log paths depending on github or package manager installed.
fix: allow 2019 and up for welcome window.
> fix: welcome window fixes

- Assets/Mirage/Weaver/Extensions.cs
- Assets/Mirage/Weaver/Resolvers.cs
I am running into this in Cubica.
> fix: null checks when types can't be resolved

- Assets/Mirage/Runtime/SocketLayer/AckSystem.cs
- Assets/Mirage/Runtime/SocketLayer/Packet.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_1stSend.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_ManySends.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_NoDroppedSends.cs
requires: https://github.com/MirageNet/Mirage/pull/852
> refactor: simplifying const values for ack system and min packet length

- Assets/Mirage/Runtime/ClientStoppedReason.cs
- Assets/Mirage/Runtime/SocketLayer/AckSystem.cs
- Assets/Mirage/Runtime/SocketLayer/Config.cs
- Assets/Mirage/Runtime/SocketLayer/Connection.cs
- Assets/Mirage/Runtime/SocketLayer/Enums/DisconnectReason.cs
- Assets/Mirage/Runtime/SocketLayer/Enums/PacketType.cs
- Assets/Mirage/Runtime/SocketLayer/Packet.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Mirage/Runtime/SocketLayer/RingBuffer.cs
- Assets/Tests/Common/TestSocketFactory.cs
- Assets/Tests/Runtime/ClientServer/NetworkClientDisconnectTest.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Fragmentation_Receive.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Fragmentation_Receive.cs.meta
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Fragmentation_Send.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Fragmentation_Send.cs.meta
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Reliable.cs
- Assets/Tests/SocketLayer/PeerTestBase.cs
- Assets/Tests/SocketLayer/PeerTestSendReceive.cs
depends on: 
- https://github.com/MirageNet/Mirage/pull/852
- https://github.com/MirageNet/Mirage/pull/853
> feat(SocketLayer): adding fragmentation to reliable sending

- Assets/Mirage/Runtime/Serialization/BitMask.cs
- Assets/Mirage/Runtime/Serialization/NetworkReader.cs
- Assets/Mirage/Runtime/Serialization/NetworkWriter.cs
Adding warning comments to methods that move position as they are error prone if used incorrectly
> feat: adding method to move position and docs comments

- doc/templates/unity/partials/navbar.tmpl.partial
- doc/templates/unity/styles/main.css
Fixed colors and some components in docfx template.
> docs: fix template

- Assets/Mirage/Runtime/ClientObjectManager.cs
this allows scene objects in first scene to be spawned
> fix: preparing client objects on connect

- Assets/Mirage/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVars.meta
- Assets/Mirage/Weaver/Processors/SyncVars/FoundSyncVar.cs
- Assets/Mirage/Weaver/Processors/SyncVars/FoundSyncVar.cs.meta
- Assets/Mirage/Weaver/Processors/SyncVars/HookMethodFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/HookMethodFinder.cs.meta
- Assets/Mirage/Weaver/WeaverExceptions.cs
requires: https://github.com/MirageNet/Mirage/pull/886
> refactor(weaver): moving some syncvar logic to new classes

- Assets/Mirage/Runtime/Messages.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
this will send it as 1 bit instead of 8 if there is no value
> perf: sending reply id as nullable

- Assets/Mirage/Weaver/Weaver.cs
requires: https://github.com/MirageNet/Mirage/pull/927
> refactor(Weaver): adding SampleScope to timer

- Assets/Mirage/Weaver/Processors/NetworkBehaviour/FoundNetworkBehaviour.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVars/BitCountFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/BitCountFromRangeFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/BitCountSerializer.cs
- Assets/Mirage/Weaver/Processors/SyncVars/BitCountSerializer.cs.meta
- Assets/Mirage/Weaver/Processors/SyncVars/BlockSizeSerializer.cs
- Assets/Mirage/Weaver/Processors/SyncVars/BlockSizeSerializer.cs.meta
- Assets/Mirage/Weaver/Processors/SyncVars/FloatPackerFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/FoundSyncVar.cs
- Assets/Mirage/Weaver/Processors/SyncVars/FunctionSerializer.cs
- Assets/Mirage/Weaver/Processors/SyncVars/FunctionSerializer.cs.meta
- Assets/Mirage/Weaver/Processors/SyncVars/PackerSerializer.cs
- Assets/Mirage/Weaver/Processors/SyncVars/PackerSerializer.cs.meta
- Assets/Mirage/Weaver/Processors/SyncVars/QuaternionFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/ValueSerializer.cs
- Assets/Mirage/Weaver/Processors/SyncVars/ValueSerializer.cs.meta
- Assets/Mirage/Weaver/Processors/SyncVars/VarIntBlocksFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/VarIntFinder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/Vector2Finder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/Vector3Finder.cs
- Assets/Mirage/Weaver/Processors/SyncVars/ZigZagFinder.cs
- Assets/Mirage/Weaver/Readers.cs
- Assets/Mirage/Weaver/Writers.cs
preparation for using bit packing in places other than syncvars
> refactor(Weaver): (DONT SQUASH) using abstract classes instead of if checks

- Assets/Mirage/Runtime/NetworkServer.cs
bite sized fix for an issue with another refactor I'm working on.
> refactor: move init to the top

- Assets/Mirage/Runtime/Serialization/WeaverAttributes.cs
- Assets/Tests/Editor/FromBitCountTest.cs
- Assets/Tests/Editor/FromBitCountTest.cs.meta
example 
```cs
[VarInt(FromBitCount.b3, FromBitCount.b7, FromBitCount.b10, true)]
```
> feat(Weaver): adding constant values for max value for number of bits

- Assets/Mirage/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Tests/Weaver/GeneratedReaderWriterTests.cs
- Assets/Tests/Weaver/GeneratedReaderWriterTests~/CanUseCustomReadWriteForAbstractClassUsedInMessage.cs
fixes: https://github.com/MirageNet/Mirage/issues/916
> fix: fixing custom reader for abstract class

- Assets/Mirage/Runtime/CharacterSpawner.cs
- Assets/Tests/Editor/CharacterSpawnerTest.cs
character spawner was registering the player prefab in awake an during scene loads this wont ever register again. Need to change it on scene changes.
Fixes #945 
Signed-off-by: dragonslaya <dragonslaya.ss@gmail.com>
> fix: character spawner fix

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/SocketLayer/Connection.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Tests/SocketLayer/PeerTest.cs
- Assets/Tests/SocketLayer/PeerTestAsClient.cs
- Assets/Tests/SocketLayer/PeerTestAsServer.cs
- Assets/Tests/SocketLayer/PeerTestConnecting.cs
- Assets/Tests/SocketLayer/PeerTestSendReceive.cs
- receiveUpdate for new message
- sendUpdate for sending batches
> perf: splitting peer update into 2

- Assets/Mirage/Runtime/SocketLayer/SocketFactory.cs
- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
Allows Address and Port to be set without knowing the type of SocketFactory being used
> feat: adding interfaces for SocketFactory so it is easier to set properties

- Assets/Mirage/Runtime/SocketLayer/Pool.cs
- Assets/Tests/SocketLayer/BufferPoolTest.cs
fixes: https://github.com/MirageNet/Mirage/issues/998
> perf: limit when pool logs when creating over max

- Assets/Mirage/Runtime/NetworkIdentity.cs
If there are Nested NetworkBehaviours and NetworkIdentity then there can be a problem where the parent NetworkIdentity will find Behaviour that belong to another child NetworkIdentity.
This will remove those NB from the current NI's array and then resize the array to be the correct size
fixes: #973
> fix(NetworkBehaviour): removing NB that belong to another NI from list

- Assets/Mirage/Components/OnlineOfflineScene.cs
> fix: setting client not ready to stop character spawning before scene change

- Assets/Mirage/Editor/Logging/LogLevelsGUI.cs
- Assets/Mirage/Editor/Logging/LogSettingChecker.cs
- Assets/Mirage/Editor/Logging/LogSettingChecker.cs.meta
- Assets/Mirage/Runtime/Logging/LogSettingsSO.cs
- removing duplicates
- updating settings from factory
- making sure classes with no namespace save/load correctly
> fix: fixing log settings that have no namespace

- LICENSE
Any objections or suggestions for this? if not I'll merge this in a week.
> chore: updating MIT License

- .github/workflows/main.yml
- Assets/Mirage/Weaver/TypeExtensions.cs
- Assets/Tests/BuildIL2CPP.meta
- Assets/Tests/BuildIL2CPP/BuildTests.cs
- Assets/Tests/BuildIL2CPP/BuildTests.cs.meta
- Assets/Tests/BuildIL2CPP/Mirage.Tests.BuildIl2CPP.asmdef
- Assets/Tests/BuildIL2CPP/Mirage.Tests.BuildIl2CPP.asmdef.meta
- Assets/Tests/Performance/Runtime/10K/BenchmarkPerformance.cs
- Assets/Tests/Performance/Runtime/10KL/BenchmarkPerformanceLight.cs
- Assets/Tests/Performance/Runtime/MultipleClients/MultipleClients.cs
- Assets/Tests/Runtime/ClientServer/GenericBehaviours.cs
- Assets/Tests/Runtime/ClientServer/GenericBehaviours.cs.meta
- Assets/Tests/Runtime/Host/NetworkSceneManagerTests.cs
- Assets/Tests/Weaver/ExtraAssembly/WeaverTestExtraAssembly.asmdef
only 7607d062720c5df1e2391e8c50e49c56e7e8fa07
requires: #1031
> ci: adding method to build test script using Il2cpp

- Assets/Mirage/Weaver/Processors/AttributeProcessor.cs
- Assets/Mirage/Weaver/Processors/RpcProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Serialization/Readers.cs
- Assets/Mirage/Weaver/Serialization/Writers.cs
- Assets/Mirage/Weaver/SerializeFunctionBase.cs
- Assets/Mirage/Weaver/TypeExtensions.cs
- Assets/Tests/Runtime/ClientServer/Generics/GenericWithSyncVar.cs
- Assets/Tests/Runtime/ClientServer/Generics/MyClass.cs
- Assets/Tests/Runtime/ClientServer/Generics/MyClass.cs.meta
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVar.cs
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVar.cs.meta
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVarEvent.cs
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVarEvent.cs.meta
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVarHook.cs
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVarHook.cs.meta
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVarHookBig.cs
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericSyncVarHookBig.cs.meta
- Assets/Tests/Weaver/SyncVarTests.cs
- doc/Articles/Guides/Generics.md
- doc/Articles/Guides/toc.yml
fixes for reverted PR https://github.com/MirageNet/Mirage/pull/1037
> (DONT SQUASH) support for generic syncvar

- Assets/Mirage/Weaver/Extensions.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Serialization/BitCountSerializer.cs
- Assets/Mirage/Weaver/Serialization/BlockSizeSerializer.cs
- Assets/Mirage/Weaver/Serialization/FunctionSerializer.cs
- Assets/Mirage/Weaver/Serialization/PackerSerializer.cs
- Assets/Mirage/Weaver/Serialization/Readers.cs
- Assets/Mirage/Weaver/Serialization/ValueSerializer.cs
- Assets/Mirage/Weaver/Serialization/ValueSerializerFinder.cs
- Assets/Mirage/Weaver/Serialization/Writers.cs
- Assets/Mirage/Weaver/SerializeFunctionBase.cs
- Assets/Tests/Runtime/ClientServer/Generics/GenericMessage.cs
- Assets/Tests/Runtime/ClientServer/Generics/GenericMessage.cs.meta
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericInstances.cs
- Assets/Tests/Runtime/ClientServer/Generics/WithGenericInstances.cs.meta
- Assets/Tests/Weaver/SyncDictionaryTests.cs
- Assets/Tests/Weaver/SyncListTests.cs
- Assets/Tests/Weaver/SyncVarTests.cs
- doc/Articles/Guides/Generics.md
Allowing writers to be creates for generic instance, eg MyType<int>
This does not work with the generic itself MyType<T> because of the way writers are registered
> feat: support for generic network messages

- Assets/Mirage/Weaver/Serialization/Readers.cs
- Assets/Mirage/Weaver/Serialization/Writers.cs
- Assets/Mirage/Weaver/SerializeFunctionBase.cs
- Assets/Tests/Common/MessageWithCustomWriter.cs
- Assets/Tests/Common/MessageWithCustomWriter.cs.meta
- Assets/Tests/Runtime/Serialization/NetworkWriterTest.cs
- Assets/Tests/Runtime/Serialization/RpcWithTypeInAnotherAssembly.cs
- Assets/Tests/Runtime/Serialization/RpcWithTypeInAnotherAssembly.cs.meta
fixes: https://github.com/MirageNet/Mirage/issues/881
> (DONT SQUASH) fix: adding const to type when writer is generated

- Assets/Mirage/Runtime/CustomAttributes.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVars/HookMethodFinder.cs
- Assets/Tests/Runtime/ClientServer/SyncVarHookWith1Arg.cs
- Assets/Tests/Runtime/ClientServer/SyncVarHookWith1Arg.cs.meta
- Assets/Tests/Runtime/SyncVarVirtualTest.cs
- Assets/Tests/Weaver/SyncVarHookTests.cs
- Assets/Tests/Weaver/SyncVarHookTests~/AutomaticFound2Methods.cs
- Assets/Tests/Weaver/SyncVarHookTests~/AutomaticHookEvent1.cs
- Assets/Tests/Weaver/SyncVarHookTests~/AutomaticHookEvent2.cs
- Assets/Tests/Weaver/SyncVarHookTests~/AutomaticHookMethod1.cs
- Assets/Tests/Weaver/SyncVarHookTests~/AutomaticHookMethod2.cs
- Assets/Tests/Weaver/SyncVarHookTests~/AutomaticNotFound.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ErrorWhenNoHookWithCorrectParametersFound.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitEvent1Found.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitEvent1NotFound.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitEvent2Found.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitEvent2NotFound.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitMethod1Found.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitMethod1FoundWithOverLoad.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitMethod1NotFound.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitMethod2Found.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitMethod2FoundWithOverLoad.cs
- Assets/Tests/Weaver/SyncVarHookTests~/ExplicitMethod2NotFound.cs
resolves: https://github.com/MirageNet/Mirage/issues/1062
> feat: syncvar hook with 1 arg

- Assets/Mirage/Runtime/NetworkServer.cs
Casting to IEnumerable will cause the Enumerator to be boxed. Using  while loop instead avoids this.
> perf: removing allocation from SendToAll

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/MessageHandler.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Runtime/SpawnDelegates.cs
- Assets/Tests/BuildIL2CPP/BuildTests.cs
- Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
- Assets/Tests/Runtime/ClientServer/ClientObjectManagerTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkIdentityTests.cs
- Assets/Tests/Runtime/Host/ClientObjectManagerHostTest.cs
- doc/docs/guides/game-objects/pickup-drop-child.md
- doc/docs/guides/game-objects/scene-objects.md
- doc/docs/guides/game-objects/spawn-object-custom.md
- doc/docs/guides/game-objects/spawn-object-pooling.md
Feature to allow getting a spawn handler at runtime from prefab hash
```cs
SpawnHandler DynamicHandle(SpawnMessage msg)
{
if (!msg.prefabHash.HasValue)
return null;
if (CheckHash(msg.prefabHash.Value)
return spawnHandler;
else
return null;
};
````
The spawnHandler could then use prefabhash to get identity from somewhere in the game.
This can be used if you are spawning many objects locally on both server and client, and need a way to link netid. 
The server can Encode some ID and send it as Prefabhash, Client can then use DynamicHandle to return a spawn handler that will Decode that Prefabhash in order to return the object that was spawned locally.
> Dynamic spawning

- Assets/Mirage/Runtime/NetworkSceneManager.cs
- Assets/Mirage/Samples~/AdditiveScenes/Scripts/ZoneHandler.cs
- Assets/Mirage/Samples~/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
- Assets/Tests/Editor/NetworkSceneManager/HostComponentTests.cs
- Assets/Tests/Editor/NetworkSceneManager/NetworkSceneManagerTests.cs
loading scene inside server methods instead of clients. this is to avoid not loading on server is host player is not in player list.
Also fixes loading parameters being missed for host mode
> fix: fixing loading scenes in host mode

- Assets/Mirage/Editor/NetworkBehaviourInspector.cs
required so users can make custom inspectors with addons like Odin
> feat: adding option to exclude NetworkBehaviourInspector

- Assets/Mirage/Runtime/NetworkSceneManager.cs
- Assets/Tests/Editor/NetworkSceneManager/NetworkSceneManagerTests.cs
some changes for https://github.com/MirageNet/Mirage/pull/1126
> refactor: improve NetworkSceneManager async tasks

- Assets/Mirage/Runtime/Serialization/MessagePacker.cs
change suggested by @imerr, see https://github.com/MirrorNetworking/Mirror/pull/3381
> perf: caching network message id

- Assets/Mirage/Runtime/CharacterSpawner.cs
CharacterSpawner is missing CompMenu tag that all other high level comps already have.
> fix: add missing CompMenu for CharacterSpawner

- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
use EXCLUDE_NANOSOCKETS as it is found in all other files
> change define name to match other instances
