- publish_upm.sh
Remove tests from npm package.  These were causing problems with other packages that also want nsubstitute
> fix: remove tests from npm package

- .github/workflows/main.yml
- Assets/Mirror/Runtime/Transport/Tcp/Server.cs
When the server is stopped,  the sockets throw a IOException, not SocketException,  so catch that and check if we got interrupted instead of reporting an errorr
> fix: interrupted server

- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Tests/Editor/MessagePackerTest.cs
Use exceptions instead of returning false for failure.
BREAKING CHANGE: MessagePacker.UnpackMessage replaced by UnpackId
> Simplify unpacking messages

- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Tests/Play/ClientServerTests.cs
- Assets/Mirror/Tests/Play/ClientServerTests.cs.meta
- Assets/Mirror/Tests/Play/FlagsTests.cs
- Assets/Mirror/Tests/Play/FlagsTests.cs.meta
- Fix [Server], [Client], [ServerCallback], [ClientCallback] firing NRE when client.active is null.
- Add code coverage
**NOTE:** Some tests are commented, because unusuable because of #68
> fix: attributes causing a NRE

- Assets/Mirror/Runtime/ClientScene.cs
Needed in case you're overriding some functions such as NetworkManager.OnClientConnect.
> Set ClientScene.server & .client as public

- Assets/Mirror/Examples/Room/Scripts/PlayerScore.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Play/NetworkServerTest.cs
BREAKING CHANGE: cannot pass GameObjects and NetworkIdentities anymore.
Will be restored in the future.
> refactor:  Client and server keep their own spawned list

- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/ShootingTankBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
This is just a small step towards removing connection id,
but it is fully self contained
BREAKING CHANGE: observers is now a set of connections, not a dictionary
> refactor: observers is now a set of connections

- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkConnectionToServer.cs
It is not possible for message to have size 0, so that check is redundant
Also, let each transport validate that the message is not to large
no need to validate it for them.  Reduces transport coupling
> refactor: Simplify message size validation

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkConnectionToServer.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/LocalConnectionTest.cs
Previously you could call networkConnection.Send(ArraySegment<byte> bytes, channelId)
This totally breaks abstraction,  NetworkConnection should _only_ deal with messages.
The problem is that if we want to send the same message to multiple connections,
we don't want to serialilize the message multiple times (very expensive).
The solution is that NetworkConnection now has a static method:
```cs
public static bool Send(IEnumerable<NetworkConnection> connections, T msg, int channelId)
```
which proceeds to send the message to all the supplied connections.
This code was previouly done in NetworkServer.
> refactor: NetworkConnection no longer accepts bytes

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Tests/Play/NetworkManagerTest.cs
This flag has nothing to do with networking,  so why is this here?
It is also on by default in the player settings.
If people want to turn this off,  let them do it in player settings or
their own scripts.
BREAKING CHANGE: NetworkManager no longer has runInBackground option
> remove runInBackground

- Assets/Mirror/Runtime/NetworkManager.cs
NetworkClient and NetworkServer's update is already called by unity
no need to call it again in LateUpdate.
Besides,  calling Update in LateUpdate is a recipe for bugs.
> remove redundant Update call

- Assets/Mirror/Runtime/NetworkDiagnostics.cs
- Assets/Mirror/Tests/Editor/NetworkDiagnosticsTests.cs
- Assets/Mirror/Tests/Editor/NetworkDiagnosticsTests.cs.meta
This class had a bit of coverage based on the testing of other classes.
With this PR it's fully covered with specific tests for it's functionality.
Additionally, there was an redundant null propagation operator where the events where being called that was removed. The event was called from inside a if block that checked for a null event.
> Improve test coverage of NetworkDiagnostics class

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkAuthenticator.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/UNetwork.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Play/NetworkManagerTest.cs
- Assets/Mirror/Tests/Play/NetworkServerTest.cs
Now you register handles with NetworkConnection instead of NetworkClient/NetworkServer
This resolves the broken abstraction at NetworkConnection level.  Now NetworkConnection deals with sending and receiving messages,  it knows how to encode and decode them with no help from the caller.
> feat: NetworkConnection manages messages handlers

- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Tests/Editor/SyncListStructTest.cs
- Assets/Mirror/Tests/Editor/SyncListTest.cs
fixes #103
BREAKING CHANGE: Sync lists no longer have a Callback event with an operation enum
> feat: synclists has individual meaningful events

- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Mirror/Tests/Editor/SyncSetTest.cs
Fixes #104 
BREAKING CHANGE: SyncSet no longer have a Callback event with an operation enum
> feat: individual events for SyncSet

- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Tests/Editor/SyncDictionaryTest.cs
Fixes #105 
BREAKING CHANGE: SyncDictionary no longer have a Callback event with an operation enum
> feat: individual events for SyncDictionary

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkConnectionToServer.cs
- Assets/Mirror/Tests/Editor/LocalConnectionTest.cs
- Make NetworkConnection.Send(ArraySegment<byte>, int channelId) internal to be able to test (the comment above the method says it's supposed to be internal not protected);
- Cover the last few lines in LocalConnection.cs that where not covered by other tests.
Should commented tests in LocalConnectionTest.cs be removed?
> Improve LocalConnection coverage

- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Null should not be used if possible.  This eliminates potential NRE accessing observers
> Make it so that observers can't be null

- Assets/Mirror/Runtime/NetworkServer.cs
Identity may be needed eg. if we need to save player data on database when disconnecting
> fix: Invoke server.Disconnected before identity is removed for its conn

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
- Assets/Mirror/Authenticators/TimeoutAuthenticator.cs
- Assets/Mirror/Runtime/INetworkConnection.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Common/LocalConnections.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTests.cs
this field is not needed anymore,  we simply don't register
handlers until the connection is authenticated.
Eliminates extra state tracking from NetworkConnections
BREAKING CHANGE: Remove NetworkConnection.isAuthenticated
> remove NetworkConnection.isAuthenticated

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Tests/Runtime/NetworkClientTest.cs
This is redundant and possible source of bugs.  You can get the
local player by calling NetworkClient.Connection.Identity
> Remove NetworkClient.localplayer

- Assets/Mirror/Tests/Runtime/ClientServerSetup.cs
- Assets/Mirror/Tests/Runtime/HostSetup.cs
- Assets/Mirror/Tests/Runtime/NetworkClientTest.cs
- Assets/Mirror/Tests/Runtime/NetworkManagerTest.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTests.cs
this change reduces re inviting the wheel for each test. Also had to remove some tests that were trying to check values before start. I will add those all back as another class since Setup cant be avoided.
I needed this to be more standard for my attempts at separating NC into two pieces. Tests were failing in all sorts of different ways due to their varying construction and initialization.
> Test cleanup

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
New event that is invoked when an object is unspawned at the server
Can be used to save the player state in persistent storage for future sessions.
Completely removes the need for the MarkForReset nonsense
> feat: onstopserver event in NetworkIdentity

- Assets/Mirror/Runtime/NetworkServer.cs
Instead of having the NetworkClient set Connection.Identity in the case of host. Have the NetworkServer set it since it has all of the same information required.
All tests passed locally and ran examples in editor as host.
> NS set identity when host

- Assets/Mirror/Runtime/NetworkManager.cs
This is a fix for the Scene Change Example. It was previously mentioned in an issue.
All tests pass locally. Currently the only test to benefit from this change is one using ServerChangeScene which is the new SceneChange example and the previous RoomManager from Mirror that has been removed from NG. But this change does not seem to negatively effect the other examples.
Host mode works in editor. To test client mode you must run everything outside the editor.
I am having an issue with connecting multiple clients in this example. Due to the logging issue I am having a hard time tracking it down.
> Dont null connection

- Assets/Mirror/Runtime/NetworkManager.cs
As mentioned in discord these messages offer no beneficial or even additional value before eventually calling the same logic that NetworkServer would provide if these did not exist.
The only user impacting change is the loss of virtual from NetworkManager. So we would either mark the calls in NetworkServer as virtual or just advise the user to replace the handler as needed with their own custom functionality.
> Remove redundant msgs from NetworkManager

- Assets/Mirror/Runtime/NetworkManager.cs
It is already set in NC under Connect and ConnectHost. The connection could not have changed during OnAuth so its useless.
NetworkClient.cs:175
NetworkClient.cs:202
> Remove NC Conn set in NetMan OnAuth

- Assets/Mirror/Runtime/NetworkClient.cs
its already set before handlers are set and never changes without also making new connections
> Simplify Client RegisterHandler

- Assets/Mirror/Runtime/NetworkClient.cs
This check is not needed:
As the compiler prevents null from being assigned:
> compiler prevents null delegates

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Tests/Runtime/ClientServerComponentTests.cs
Change order of if statement to allow handler to be used before default.
All tests passed locally. Tested with Tanks example for default behaviour. No examples for spawnhandler exist at this time.
Was also tested in a game as part of the fix for issue #222.
> fix: Spawn Handler Order

- Assets/Mirror/Runtime/NetworkClient.cs
Checking the state and contents of these Dictionaries represents a good chunk of the uncovered code for NC.
The only other solution I could think of was a new NC that has methods to expose the private stuff. But with the HostSetup it would mean a second test structure to do the same thing. Setting this internal is much less of a mess.
If there is a better way please let me know.
> NC accessibility changes to allow easier testing

- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
A minor quality of life addition would be to add two new attributes for HasAuthority and IsLocalPlayer. 
I personally check for authority quite frequently as a safeguard and an attribute would speed up my workflow a bit. 
One could also see it as a way to "complete the set" since there's already attributes for checking if the object is a server and client, so why not if it is a local player or it has authority?
The attributes are just `[HasAuthority]` and `[LocalPlayer]`. Callback versions are also provided.
For now, the weaver instructions have been put in the ServerClientAttributeProcessor class as I didn't want to edit too much in the weaver. A change that could make sense with the addition of these attributes is to rename the ServerClientAttributeProcessor class to something like …
> feature: Add weaver attributes for HasAuthority and IsLocalPlayer

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
- Assets/Mirror/Tests/Editor/NetworkManagerTest.cs.meta
Also changed OnValidate to Reset in NetworkManager since it only needs to be run once.
NetworkManager, NetworkClient, and NetworkServer now gets all the scripts they needed when they are added. For example, NetworkManager gets the NetworkClient and NetworkServer script that is added due to the RequireComponent attribute.
> Fields in NetworkManager, NetworkServer, and NetworkClient are now set when created.

- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Now that Transports are auto assigned this cause tests to fail as the un-Initialized Transport should not be asked to disconnect.
> fix: test added a Transport but never actually used it

- Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
- Assets/Mirror/Examples/Basic/Scenes/Example.unity
- Assets/Mirror/Examples/ChangeScene/Scenes/Main.unity
- Assets/Mirror/Examples/Chat/Scenes/Main.unity
- Assets/Mirror/Examples/Discovery/Scenes/Scene.unity
- Assets/Mirror/Examples/ListServer/Scenes/Scene.unity
- Assets/Mirror/Examples/Pong/Scenes/Scene.unity
- Assets/Mirror/Examples/RunInBackground.cs
- Assets/Mirror/Examples/RunInBackground.cs.meta
- Assets/Mirror/Examples/Tanks/Scenes/Scene.unity
When testing Examples in a separate build when not in focus they would freeze and disconnect. RunInBackground was part of NetMan in the past but was removed as its not really part of Networking but it is needed for the Examples to work properly. So I added it as a script under the Mirror.Examples namespace and added it to all of the existing Examples.
> fix: examples run in background

- Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
> fix: Additive Scene Example was missing Player Auth on movement.

- Assets/Mirror/Runtime/NetworkManager.cs
For some reason, the `loadingSceneAsync` field gets serialized in 2020.1 (might be a bug?) but to be extra safe, add a NonSerialized attribute to it to be 100% sure it stops it from being serialized.
When it gets serialized it causes an ArgumentNullException to be thrown internally in Unity.
> Stop scene loading operation from being serialized

- Assets/Mirror/Components/NetworkSceneChecker.cs
- Assets/Mirror/Editor/Weaver/Processors/MonoBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/ShootingTankBehaviour.cs
- Assets/Mirror/Examples/Basic/Scripts/Player.cs
- Assets/Mirror/Examples/Benchmarks/10k/Scripts/Health.cs
- Assets/Mirror/Examples/Benchmarks/2k NetworkTransforms/Scripts/MonsterMovement.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsCollision.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Reward.cs
- Assets/Mirror/Examples/Pong/Scripts/Ball.cs
- Assets/Mirror/Examples/Tanks/Scripts/Projectile.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMonoBehaviourTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMonoBehaviourTests~/MonoBehaviourServerCallback.cs
- Assets/Mirror/Tests/Runtime/GuardsTests.cs
- Assets/Resources.meta
- doc/Guides/Attributes.md
- doc/Guides/NetworkBehaviour.md
If you want to get an error you do this:
```cs
[Server]
public void ServerFunctionOnly() {}
```
If you don't want to get an error, you do this:
```cs
[Server(error = false)]
public void ServerFunctionOnly() {}
```
BREAKING CHANGE: [ServerCallback] is now [Server(error = false)]
> feat: Server attribute now throws error

- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/NetworkBehaviourHasAuthority.cs
- Assets/Mirror/Tests/Runtime/GuardsTests.cs
If you want to get an error you do this:
```cs
[HasAuthority]
public void ClientFunctionOnly() {}
```
If you don't want to get an error, you do this:
```cs
[HasAuthority(error = false)]
public void ClientFunctionOnly() {}
```
BREAKING CHANGE: [HasAuthorityCallback] is now [HasAuthority(error = false)]
> feat: HasAuthority attribute now throws error

- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/NetworkBehaviourLocalPlayer.cs
- Assets/Mirror/Tests/Runtime/GuardsTests.cs
If you want to get an error you do this:
```cs
[LocalPlayer]
public void LocalPlayerFunctionOnly() {}
```
If you don't want to get an error, you do this:
```cs
[LocalPlayer(error = false)]
public void LocalPlayerFunctionOnly() {}
```
BREAKING CHANGE: [LocalPlayerCallback] is now [LocalPlayer(error = false)]
> feat: LocalPlayer attribute now throws error

- Assets/Mirror/Runtime/Transport/AsyncFallbackTransport.cs
- Assets/Mirror/Runtime/Transport/AsyncMultiplexTransport.cs
- Assets/Mirror/Runtime/Transport/AsyncTcp/AsyncTcpTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Mirror/Runtime/Transport/Websocket/AsyncWsTransport.cs
- Assets/Mirror/Tests/Common/LoopbackTransport.cs
- Assets/Mirror/Tests/Common/MockTransport.cs
- Assets/Mirror/Tests/Editor/Transport/AsyncFallbackTransportTest.cs
- Assets/Mirror/Tests/Editor/Transport/AsyncMultiplexTransportTest.cs
Transports now have a Supported property, which is true if the transport works on the current platform.
For example, TCP is supported everywhere except WebGL
> feat: Transports can tell if they are supported

- Assets/Mirror/Runtime/NetworkClient.cs
NetworkClient.cs:615 "identity.Server = hostServer" - is set under Client.ApplySpawnPayload
ApplySpawnPayload is private and only has 1 ref under OnSpawn
OnSpawn is an internal method that is a registered message handler only in client mode.
Therefor NetworkClient.cs:615 "identity.Server = hostServer" will always be null.
Removing this line will leave it null just the same.
> remove hostServer set as its never not null

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/Transport/AsyncFallbackTransport.cs
- Assets/Mirror/Runtime/Transport/AsyncMultiplexTransport.cs
- Assets/Mirror/Runtime/Transport/AsyncTcp/AsyncTcpTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Mirror/Runtime/Transport/Websocket/AsyncWsTransport.cs
- Assets/Mirror/Tests/Common/LoopbackTransport.cs
- Assets/Mirror/Tests/Common/MockTransport.cs
- Assets/Mirror/Tests/Editor/Transport/AsyncFallbackTransportTest.cs
- Assets/Mirror/Tests/Editor/Transport/AsyncMultiplexTransportTest.cs
- Assets/Mirror/Tests/Editor/Transport/AsyncTransportTests.cs
- Assets/Mirror/Tests/Runtime/ClientServerSetup.cs
for example,  Websocket transport supports ws and wss
and multiplex transport support anything that the child transports support
> feat: Transports may support any number of schemes

- Assets/Mirror/Runtime/INetworkSceneManager.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/PlayerSpawner.cs
- Assets/Mirror/Tests/Runtime/NetworkSceneManagerTests.cs
This would either apply to a ClientOnly or a HostClient. In both cases the method internally calls the client.Connection so there is no need to pass one in as it would be the same anyway.
Removed NULL test as that case is no longer possible.
> breaking: remove SetClientReady conn as its known

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Lymdun reported issue in discord where a scene object in host mode would always have a null Client.
This PR fixes that issue due to ActivateHostScene() being called in NetworkManager under StartHostClient(). The test struct for NetworkIdentity has a bad Setup. Will attempt to clean up that file to add tests for this fix.
> fix: moved SpawnObjects call for hostmode to after LocalClient Connected

- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/PlayerSpawner.cs
- Assets/Mirror/Tests/Runtime/NetworkSceneManagerTests.cs
This logic is already covered by NetworkConnection.IsReady. It represents when a scene load is either in progress (false) or completed (true)
> breaking: remove redundant scene ready value

- Assets/Mirror/Editor/Weaver/CompilationFinishedHook.cs
- Assets/Tests/Editor/Weaver/WeaverAssembler.cs
- Assets/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
- Assets/Tests/Editor/Weaver/WeaverTests.cs
uwee reported these errors:
```cs
TestingScriptableObjectArraySerialization (0.501s)
---
SetUp :   Expected: False
But was:  True
SetUp : Unhandled log message: '[Error] Assets\Tests\Editor\Weaver\WeaverGeneralTests~\TestingScriptableObjectArraySerialization.cs:22 -- Assets\Tests\Editor\Weaver\WeaverGeneralTests~\TestingScriptableObjectArraySerialization.cs(22,25): error CS0433: The type 'ScriptableObject' exists in both 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null''. Use UnityEngine.TestTools.LogAssert.Expect
---
Weaver: stop because compile errors on target
Assets\Tests\Editor\Weaver\WeaverGeneralTests~\TestingScriptableObjectArraySerialization.cs:22 -- …
```
> tests: fix weaver tests in windows

- Assets/Mirror/Runtime/NetworkSceneManager.cs
The server should always send its currently active scene to the client. This prevents situations where you are forced to make your server change scenes just to populate a string so the client is also told to sync up.
> Always Send NetworkSceneName

- Assets/Mirror/Components/Discovery/NetworkDiscoveryHUD.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkManagerHud.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Samples~/Chat/Scripts/ServerWindow.cs
- Assets/Tests/Performance/Runtime/BenchmarkPerformance.cs
- Assets/Tests/Performance/Runtime/BenchmarkPerformanceLight.cs
- Assets/Tests/Runtime/HostSetup.cs
- Assets/Tests/Runtime/NetworkClientTest.cs
- Assets/Tests/Runtime/NetworkManagerTest.cs
- Assets/Tests/Runtime/NetworkServerTests.cs
Before this change you needed to have a NetworkManager to be able to run in Host mode. Now you can do that fully from a NetworkServer and NetworkClient.
There are other potential simplifications in the host related code in NS/NC
To fix this breaking change via your existing NetworkManager simply replace:
networkManager.StartHost();
networkManager.server.StartHost(networkManager.client);
> breaking: NetworkServer Host Mode

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Every frame we loop through all network objects and ask them to synchronize.
This is very wasteful, as network objects should not normally change very often.
This PR changes it so that we keep track of objects that are dirty, and we synchronize only those.  On average,  this changes synchronization from O(n) to near O(1).
In my MAC in 10klight example:
Time Microsecond Median:7807.40 Min:4853.10 Max:11369.00 Avg:8011.55 Std:1266.32 SampleCount: 240 Sum: 1922772.50
Time Microsecond Median:4016.30 Min:2247.10 Max:16143.50 Avg:4916.15 Std:2525.00 SampleCount: 240 Sum: 1179876.40
> perf: Only synchronize dirty objects

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Editor/MessageTests.cs
Before:
when I connection is established, we spawned the objects like this:
1) ObjectSpawnStartedMessage
2) SpawnMessage
3) SpawnMessage
...
n) SpawnMessage
n+1) ObjectSpawnFinishdMessage (and initialize all objects)
After:
when I connection is established, we spawned the objects like this:
1) SpawnMessage (initialize)
2) SpawnMessage (initialize)
3) SpawnMessage (initialize)
...
n) SpawnMessage (initialize)
BREAKING CHANGE: It is no longer guaranteed that all objects are spawned before we start calling events
> perf: Remove 2 messages when player connects

- Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
Previously we initialized syncobjects, so this is valid:
```cs
public class Pepe : NetworkBehavior {
public SyncList<int> mylist;
}
```
With this change,  users must initialize their own fields:
```cs
public class Pepe : NetworkBehavior {
public SyncList<int> mylist = new SyncList<int>();
}
```
BREAKING CHANGE: You must initialize all your SyncLists
> Users must initialize SyncLists

- Assets/Mirror/Runtime/Transport/Kcp/Crc64.cs
- Assets/Mirror/Runtime/Transport/Kcp/Crc64.cs.meta
- Assets/Mirror/Runtime/Transport/Kcp/KcpConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/Utils.cs
Every message now is verified with a CRC64 checksum.
This makes it practically immune to corruption.
Note that UDP has a CRC16 built-in,  which does make it possible for corruption to go undetected.
The performance impact seems completely negligible.
> feat: KCP transport now has CRC64 validation

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Tests/Editor/SyncVarTest.cs
- Assets/Tests/Runtime/NetworkBehaviourTests.cs
Accessing a syncvar network identity before the object is spawned gives NRE
fixes #399
> fix: reading and writing a network identity before spawning

- Assets/Mirror/Runtime/Transport/Kcp/HashCash.cs
- Assets/Mirror/Runtime/Transport/Kcp/HashCash.cs.meta
- Assets/Mirror/Runtime/Transport/Kcp/KcpClientConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpServerConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
- Assets/Tests/Performance/Runtime/MultipleClients/Scenes/Scene.unity
- Assets/Tests/Runtime/Transport/HashcashTest.cs
- Assets/Tests/Runtime/Transport/HashcashTest.cs.meta
Implementing hashcash to prevent DoS attacks.
In the handshake,  the client must mine and provide a valid Hashcash token.  The server will validate the token before opening the connection.
> feat: DoS prevention

- Assets/Mirror/Runtime/Transport/Kcp/ByteBuffer.cs
- Assets/Mirror/Runtime/Transport/Kcp/Segment.cs
We had 2 object pools,  one for ByteBuffer and one for Segment
There is no need for this at all,  just have a pool for Segment
and keep it's buffer.
> Remove redundant pool for ByteBuffer

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Tests/Editor/NetworkWriterTest.cs
- Assets/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
The code to serialize lists, arrays, and array segments is now in the runtime instead of generated in the weaver.
Saves a lot of hard to understand code
> simplify serializing collections

- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Tests/Editor/MessagePackerTest.cs
- Assets/Tests/Editor/NetworkConnectionTest.cs
- Assets/Tests/Editor/NetworkConnectionTest.cs.meta
display user-friendly log with an unexpected messages.  
> Unknown message ID 1234 connection(...). May be due to no existing RegisterHandler for this message.
> "Unexpected message Mirror.SceneMessage received in connection(...). Did you register a handler for it?"
> feat: display user-friendly log with an unexpected messages.

- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/PlayerSpawner.cs
- Assets/Mirror/Samples~/AdditiveScenes/Scenes/MainScene.unity
- Assets/Tests/Editor/PlayerSpawnerTest.cs
- Assets/Tests/Runtime/LobbyReadyTest.cs
- Assets/Tests/Runtime/NetworkSceneManagerTests.cs
This PR fixes a handful of related timing issues with scene loading. I tried to break this up in other smaller PRs but this chunk is too tangled. The intent is not to change functionality or flow but instead fix bugs or oversights in the existing code.
-----
Before: FinishLoadScene would fire before scene change actually completed
After: hook AsyncOperation.Complete to wait for completion.
Reason for change: this was the original inspiration for the change [Unity Developer Forum Post](https://forum.unity.com/threads/scenemanager-loadscene-additive-and-set-active.380826/#post-2486533). After some testing I confirmed that the UnityEvents for Post scene change were firing before the scene change completed in some scenarios. This was hidden by the IsReady code.
-----
Before: On connect the …
> fix: fix multiple scene loading order issues

- Assets/Mirror/Runtime/Transport/Tcp/TcpConnection.cs
- Assets/Mirror/Runtime/Transport/Tcp/TcpTransport.cs
- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/HeadlessBenchmark.cs
- Assets/Tests/Runtime/Transport/TransportTests.cs
KCP transport is better than TCP transport in every way as far as I know.  
There is no reason to use TCP transport anymore.
Let's mark it obsolete so people know to migrate.
> feat: TCPTransport is obsolete, use KCPTransport instead

- Assets/Mirror/Runtime/INetworkSceneManager.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Samples~/AdditiveScenes/Scripts/ZoneHandler.cs
- Assets/Mirror/Samples~/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
- Assets/Tests/Editor/MessagePackerTest.cs
- Assets/Tests/Runtime/NetworkSceneManagerTests.cs
before #418 it was not clear if the scene being sent in the msg was a name or a path. Now NG expects it to be a path. This change cleans up the comments and variable names to more clearly show that expectation.
Also should resolve code smell for complexity on ApplySceneOperation.
> fix: names and refs clear that PATH should be sent in scene msg

- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Tests/Editor/SyncDictionaryTest.cs
- Assets/Tests/Editor/SyncListTest.cs
- Assets/Tests/Editor/SyncSetTest.cs
Previously, synclists were not raising events when the object was spawned in the client.
This confused a lot of people.  Now they do,  to receive the event, subscribe to it in the Awake() method (before the data is synchronized).
> feat: SyncObjects raise events when initialized

- Assets/Mirror/Runtime/NetworkReaderPool.cs
- Assets/Mirror/Runtime/NetworkWriterPool.cs
Sealed classes don't need the complicated disposable pattern
> perf: simplify NetworkWriter/Reader dispose

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Editor/NetworkIdentityTests.cs
- Assets/Tests/Editor/SyncVarTest.cs
NetworkIdentity DirtyComponentsMask code removed entirely. OnSerialize now includes the component index as byte before serializing each component. Faster because we avoid GetDirtyComponentsMask() and GetSyncModeObserversMask() calculations. Increases allowed NetworkBehaviour components from 64 to 255. Code is significantly more simple. (#2331)
* perf: NetworkIdentity DirtyComponentsMask code removed entirely. OnSerialize now includes the component index as byte before serializing each component. Faster because we avoid GetDirtyComponentsMask() and GetSyncModeObserversMask() calculations. Increases allowed NetworkBehaviour components from 64 to 255. Bandwidth is now smaller if <8 components, and larger if >8 components. Code is significantly more simple.
* Update …
> perf: faster component serialization/deserialization

- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/Transport/IConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/Kcp.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpClientConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpServerConnection.cs
- Assets/Mirror/Runtime/Transport/PipeConnection.cs
- Assets/Tests/Editor/PipeConnectionTest.cs
- Assets/Tests/Runtime/Transport/KcpTransportTest.cs
- Assets/Tests/Runtime/Transport/TransportTests.cs
before ReceiveAsync returned both a boolean and a channel.
This was very awkard to use and implement,  now ReceiveAsync throws EndOfStreamException
when the connection is disconnected
BREAKING CHANGE: External transports will need update
> ReceiveAsync now throws EndOfStreamException

- Assets/Mirror/Editor/Weaver/Processors/CodePass.cs
- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Tests/Runtime/BasicAuthenticatorTest.cs
- Assets/Tests/Runtime/BasicAuthenticatorTest.cs.meta
Basic authenticator was failing because the weaver did not save the generated reader/writer.
fixes #441
> fix(weaver): NRE with basic authenticator

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
Scenario: Server starts and is running SceneA. Client1 connects and is told to load SceneA also. Server does an additive load and SceneB is loaded on both Server and Client1. Client2 then connects.
Before: Client2 loads SceneA and then gets errors for object updates for objects in a SceneB as it was not told to load that scene by the server.
After: Client2 is told to load SceneA and additively load SceneB. Then spawn all objects in all scenes.
> feat: server sends list of additive scenes upon connect

- Assets/Mirror/Editor/Weaver/Mirror.Weaver.asmdef
IDE complains about missing assembly reference in ReaderWriterProcessor.GenerateReadersWriters() because three nameof expressions reference async methods that return UniTask.
Unity Editor doesn't seem to care, but added the UniTask asmdef reference to silence the IDE errors.
> fix: add missing UniTask.asmdef reference to Mirror.Weaver.asmdef

- Assets/Tests/Runtime/NetworkServerTests.cs
seems like UnityEvents cannot fire after Application.isQuitting == true.
Breakpoints in the call path all hit. The invoke never happens.
> bug: Stopped event never fires

- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ServerRpcProcessor.cs
Makes it safer because we don't end up with null methods in
unexpected places.
> Add empty skeleton method instead of null

- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
Previously,  if a client sends a valid hello and nothing else,
the server waits to complete the handshake before accepting other connections.
This opens a very easy to exploit DoS vector, because a single client can prevent the server from accepting other connections.
Now,  the server fires a separate task for completing the handshake for each client. It does not consider the connection accepted until the handshake is completed.
This way, if a client does not cooperate with the handshake, other clients can still be accepted
> fix: DoS vector in kcp accept

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkServer.cs
On NC it was not actually setting the value of the comp found via GetComponent. That would cause the following try to throw an NRE when you tried to connect. Now it throws for the same reason but gives a specific line and reason in the debug message. Much easier to debug. The same logic was applied to the server side.
> fix: better transport checks on NS and NC

- Assets/Mirror/Editor/ClientObjectManagerInspector.cs
- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/INetworkClient.cs
- Assets/Mirror/Runtime/PlayerSpawner.cs
- Assets/Mirror/Runtime/UNetwork.cs
- Assets/Mirror/Samples~/AdditiveScenes/Scenes/MainScene.unity
- Assets/Mirror/Samples~/Basic/Scenes/Example.unity
- Assets/Mirror/Samples~/ChangeScene/Scenes/Main.unity
- Assets/Mirror/Samples~/Chat/Scenes/Main.unity
- Assets/Mirror/Samples~/Discovery/Scenes/Scene.unity
- Assets/Mirror/Samples~/MultipleAdditiveScenes/Scenes/Main.unity
- Assets/Mirror/Samples~/Pong/Scenes/Scene.unity
- Assets/Mirror/Samples~/RigidbodyPhysics/Scenes/BounceScene.unity
- Assets/Mirror/Samples~/Tanks/Scenes/Scene.unity
- Assets/Tests/Editor/ClientObjectManagerInspectorTest.cs
- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/HeadlessBenchmark.cs
- Assets/Tests/Performance/Runtime/MultipleClients/MultipleClients.cs
- Assets/Tests/Runtime/ClientObjectManagerTest.cs
- Assets/Tests/Runtime/ClientServerComponentTests.cs
- Assets/Tests/Runtime/ClientServerSetup.cs
- Assets/Tests/Runtime/ServerObjectManagerTest.cs
BREAKING CHANGE: Now you can only assign prefabs with NetworkIdentity to the ClientObjectManager
> ClientObjectManager now requires NetworkIdentity

- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Tests/Runtime/HostComponentTests.cs
To reproduce:
1) open the basic example
2) start host mode
3) stop network
4) start host mode
I expect the player to be spawned the second time too.
but no player is spawned.
Here is a unit test that I believe reproduces the root cause
> fix: Restarting host does not start player

- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Tests/Common/LoopbackTransport.cs
- Assets/Tests/Common/MockTransport.cs
- Assets/Tests/Performance/Runtime/10K/BenchmarkPerformance.cs
- Assets/Tests/Performance/Runtime/10KL/BenchmarkPerformanceLight.cs
- Assets/Tests/Performance/Runtime/MultipleClients/MultipleClients.cs
- Assets/Tests/Runtime/ClientServerSetup.cs
- Assets/Tests/Runtime/HostComponentTests.cs
- Assets/Tests/Runtime/HostSetup.cs
- Assets/Tests/Runtime/Transport/KcpTransportTest.cs
- Assets/Tests/Runtime/Transport/MultiplexTransportTest.cs
- Assets/Tests/Runtime/Transport/TransportTests.cs
These changes are designed so that transports can be stacked on top of each other
and each middleware transport can implement their own handshake.
BREAKING CHANGE: Add Connected event to Transport API
BREAKING CHANGE: Add Started event to Transport API
BREAKING CHANGE: ListenAsync returns a task that completes when the transport stops
BREAKING CHANGE: Remove AcceptAsync from transports
> Transport now has connected and started events.

- Assets/Mirror/Editor/ClientObjectManagerInspector.cs
In dragon's game,  this can consume upwards of 30 GB of RAM
> fix: don't consume so much memory registering prefabs

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
Generating readers and writers for structs in other assemblies
could sometimes cause a
```
System.ArgumentException: Member 'xxx' is declared in another module and needs to be imported
```
This in particular affected unity mathematics.
> fix: using mathematics in commands and rpcs

- Assets/Mirror/Runtime/Compression.cs
- Assets/Mirror/Runtime/Compression.cs.meta
- Assets/Tests/Editor/Compression.cs
- Assets/Tests/Editor/Compression.cs.meta
as described by
https://gafferongames.com/post/snapshot_compression/
Assuming quaternions are normalized, this algorithm gets a 29-bit lossy compression of quaternions suitable for networking rotations.  Note that a full-blown quaternion takes 32 * 4 = 128 bits
> feat: Quaternion compression

- Assets/Mirror/Runtime/NetworkTime.cs
- Assets/Mirror/Samples~/Basic/Scenes/Example.unity
By leveraging unreliable channel,  the ping can significantly improve
which makes time synchronization a lot more accurate.
Before (85 ms):
After (16 ms):
This also demonstrates why we want to use unreliable channel for movement.
> perf: Ping now goes through unreliable channel

- Assets/Mirror/Runtime/NetworkReader.cs
Make sure array length is within a reasonable size
> fix: prevent DoS attacks with invalid array length

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
As discussed in discord,  removing this flag.
Changing this flag at runtime does not work at all.
and it is also bugged,  see #389
The use case this addresses is to have an object that only lives in the server
but you can easily achieve this by setting an object as active
in the Started and Stopped events in NetworkServer.
In the future, we may reintroduce this if there is a good case for it
with an AOI rewrite
closes #389
BREAKING CHANGE: Remove serverOnly option in NetworkIdentity
> breaking: remove serverOnly

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkReaderPool.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/NetworkClientTest.cs
As far as I know,  this is the last piece of static state we have.
Instead of having it as a static, which could cause trouble with
multiple tasks,  when we receive a message, we attach the current
NetworkClient and NetworkServer to NetworkReader.
A custom deserializer,  can ask the reader for the NC or NS and use
it to lookup NetworkIdentities.
> Remove static NC.Current and NS.Current

- .releaserc.yml
- Assets/Mirror/Runtime/AssemblyInfo.cs
To access MirrorNG runtime version,  you can use:
```
typeof(NetworkIdentity).Assembly.GetName().Version.ToString()
```
> feat: Provide mirrorng version at runtime

- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Runtime/GameObjectSyncvar.cs
- Assets/Mirror/Runtime/GameObjectSyncvar.cs.meta
- Assets/Tests/Editor/Weaver/WeaverSyncVarHookTests.cs
- Assets/Tests/Editor/Weaver/WeaverSyncVarHookTests~/FindsHookWithGameObject.cs
- Assets/Tests/Runtime/GameObjectSyncvarTest.cs
- Assets/Tests/Runtime/GameObjectSyncvarTest.cs.meta
GameObjects can now be synchronized from server to client.
They also support lazy loading,  so if a gameobject has not been spawned yet
it will still return the correct GO when it is eventually spawned
> feat: Support gameobjects in syncvars

- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Runtime/NetworkBehaviorSyncvar.cs
- Assets/Mirror/Runtime/NetworkBehaviorSyncvar.cs.meta
- Assets/Tests/Editor/Weaver/WeaverSyncVarTests.cs
- Assets/Tests/Runtime/NetworkBehaviorSyncvarTest.cs
- Assets/Tests/Runtime/NetworkBehaviorSyncvarTest.cs.meta
Similar to NetworkIdentity and GameObjects, now we can synchronize
NetworkBehaviors in a lazy fashion.  Meaning even if the target
object is spawned at a later time, it will still be found
> feat: SyncVar support arbitrary NetworkBehavior

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
These are giving NullReferenceException,  they should not be
necesary because unityevents automatically removes subscribers
when they are destroyed.
> fix: null reference destroying objects

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Weaver/Readers.cs
- Assets/Mirror/Weaver/Writers.cs
- Assets/Tests/Runtime/ClientServer/NetworkBehaviorRpcTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkBehaviorRpcTest.cs.meta
- Assets/Tests/Weaver/WeaverNetworkBehaviourTests.cs
- Assets/Tests/Weaver/WeaverNetworkBehaviourTests~/NetworkBehaviourChild.cs
It is now valid to send NetworkIdentity, NetworkBehaviors and GameObjects as RPC parameters.
NG will serialize the gameobject id and component index where appropriate and do the lookup in the other side.
> feat: send NI, NB and GO in RPC

- Assets/Mirror/Runtime/NetworkClient.cs
Adds a simple overload to easily allow the user to connect to a server through a different port. Mainly just a method for the lazy, like me, or the ones that really don't know how to use the Uri builder. It makes joining different ports a bit more accessible.
> feat: Add ConnectAsync overload with port.

- Assets/Mirror/Weaver/Processors/SyncVarProcessor.cs
- Assets/Tests/Runtime/ClientServer/NetworkIdentitySyncvarTest.cs
Test and fix this error:
: Closed connection: connection(127.0.0.1:0). Invalid message System.InvalidProgramException:
Invalid IL code in Mirror.Tests.ClientServer.SampleBehaviorWithNI:DeserializeSyncVars (Mirror.NetworkReader,bool): IL_0057: callvirt  0x06000570
> fix: invalid IL with NI syncvars with hooks

- Assets/Mirror/Weaver/Extensions.cs
Unity is generating this error
> The same field name is serialized multiple times in the class or it's parent class.
> This is not supported: Base(NetworkTransform) SYNC_VAR_COUNT
when you have a multiple levels of inheritance in network behaviours
> fix: error saving field name SYNC_VAR_COUNT

- Assets/Mirror/Weaver/MirrorILPostProcessor.cs
Avoid weaving editor scripts including Assembly-CSharp-Editor.dll
We were already not expecting editor scripts to be weaved,  but this actively prevents it. 
Speeds up weaving a few seconds
> perf: avoid weaving editor scripts

- Assets/Mirror/Editor/NetworkMenu.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/HeadlessBenchmark.cs
- Assets/Tests/Runtime/ClientServer/ClientServerSetup.cs
BREAKING CHANGE: rename NetworkServer.transport to NetworkServer.Transport
> style: rename NetworkServer Transport to follow casing rules

- Assets/Mirror/Runtime/Transport/Kcp/KcpServerConnection.cs
- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Tests/Runtime/Transport/KcpTransportTest.cs
KCP transport reports how many bytes were sent and received.
This can be used to report bandwidth.
Other transports can override these properties to report bandwidth too.
> feat: transports can report bandwidth

- Assets/Mirror/Runtime/INetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NotifyPacket.cs
- Assets/Mirror/Runtime/NotifyPacket.cs.meta
- Assets/Tests/Runtime/Serializers/NetworkConnectionTest.cs
From the receiver it is the same as any other message:
```cs
connection.RegisterHandler<SomeMessage>( (message) => {
// I received a message 
});
```
From the sender, it looks like this:
```cs
connection.NotifyDelivered += (connection, token) => {
Debug.Log($"the message with token {token} has been delivered");
};
connection.NotifyLost += (connection, token) => {
Debug.Log($"the message with token {token} has been lost");
};
connection.SendNotify(new SomeMessage(...),  "my token");
```
If you send a message,  you will eventually get one of those callbacks.  Messages are always delivered in order.  There is no guarantee that messages are delivered (but you can just resend in the lost callback if you want).  Same latency as raw unreliable.
> feat: notify algorithm in connection

- Assets/Mirror/Runtime/NetworkBehaviour.cs
small performance gain in rpcs for objects with lots of network behaviors (such as cubica :) )
Thanks to Punfish who found it.
> perf: cache component index in network behavior

- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
normal delay mode has proven to cause issues in bench tests and user games. After more testing and feedback a default of Fast3 seems to be much more stable and performant stopping all choke warnings.
> feat: recommend Fast3 as default for performance

- Assets/Mirror/Cloud/Core/Events.cs
- Assets/Mirror/Cloud/Core/JsonStructs.cs
- Assets/Mirror/Cloud/ListServer/ListServerJson.cs
- Assets/Mirror/Components/Experimental/NetworkTransformBase.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Runtime/InvalidMessageException.cs
- Assets/Mirror/Runtime/LogSettings.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Weaver/MirrorILPostProcessor.cs
- Assets/Mirror/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Weaver/WeaverExceptions.cs
weaving mirror runtime is proving to be problematic.
It requires us to do a reload all every time we change things,
and it does not get weaved proberly with LEGACY_ILPP, which could be
a workaround for rewired compatibility.
> refactor(weaver): mirror runtime no longer needs weaver

- Assets/Mirror/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Tests/Weaver/GeneratedReaderWriterTests.cs
- Assets/Tests/Weaver/GeneratedReaderWriterTests~/CreateForExplicitNetworkMessage.cs
- Assets/Tests/Weaver/GeneratedReaderWriter~/CreateForExplicitNetworkMessage.cs
Normally MirrorNG detects what is a message and creates an id for it.
This PR allows you to explicitly declare a class or struct as a network message
This can be useful when you are making a generic class (such as Discovery)
to explicitly mark a class/struct as a network message you can do:
```cs
[NetworkMessage]
public struct MyMessage {
...
}
```
> feat: explicit declaration of network messages

- Assets/Mirror/Runtime/Transport/Kcp/KcpTransport.cs
fixes the 10 seconds of SocketException spam when a client disconnects without a goodby msg. Confirmed as a fix via HeadlessBenchmark testing.
> fix: client throwing exception when force disconnecting

- Assets/Mirror/Runtime/NetworkServer.cs
- This message should be a warning so that it is logged by default.
- Server being full is something the developer should look into, therefor should be a warning
> fix: increase log level of full server

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkSceneManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
This PR changes the position of serializable fields in the components that are attached to NetworkManager. For example, the transport field in NetworkServer has been moved above the events. The events take up a lot of space and this prevents the user from having to scroll to the bottom of the component to set a field.
> style: reorder positions of serializable fields in networkmanager components

- Assets/Mirror/Runtime/Transport/Kcp/KcpConnection.cs
ps: not sure what PR title prefix should be
> refactor: simplify delay call in kcpconnection.tick

- Assets/Mirror/Runtime/INetworkServer.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Samples~/AdditiveScenes/Scripts/ZoneHandler.cs
- Assets/Mirror/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Tests/Runtime/ClientServer/NetworkServerTests.cs
NetworkServer should not have to deal with NetworkIdentities or their
owners.
Remove SendToClientOfPlayer method,  it doesn't add value.
BREAKING CHANGE: SendToClientOfPlayer removed.  Use identity.ConnectionToClient.Send() instead
> refactor: separate player ownership from NetworkServer

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
NetworkServer should be usable without NetworkIdentities or observer lists.
So the SendToObservers method is moved to NetworkIdentity
> refactor: remove SendToObservers from NetworkServer

- Assets/Mirror/Runtime/ClientObjectManager.cs
- Assets/Mirror/Runtime/GameObjectSyncvar.cs
- Assets/Mirror/Runtime/NetworkBehaviorSyncvar.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkIdentitySyncvar.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkReaderPool.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/GameObjectSyncvarTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkBehaviorSyncvarTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkIdentitySyncvarTest.cs
NetworkReader no longer has a hardcoded dependency on NetworkClient and NetworkServer.
rather the NetworkReader has an IObjectLocator, which can be any class
that can find objects by netid.
BREAKING CHANGE: NetworkReader no longer have .Client and .Server, it has a .ObjectLocator instead
> refactor: readers no longer depends on NetworkClient and NetworkServer

- Assets/Mirage/Runtime/NetworkSceneManager.cs
related to #587.
Without cutting any deeper I am ok with adding the option but defaulting it to enabled for now. I still think the current behavior is what most people would use. If not its a simple check box to change it :)
!!!NOTE: If you disable the DDOL setting for NetworkSceneManager and do a Normal (non additive) scene change you will need to take extra steps to ensure your Network containing GameObject is not destroyed in that operation!!!
> feat: optional dontdestroyonload for networkscenemanager

- Assets/Mirage/Runtime/PlayerSpawner.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
fix: #586
I used the Tanks example and just deleted the NetworkSceneManager component and hit play. After these changes everything works as normal.
> feat: make networkscenemanager optional again

- Assets/Mirage/Weaver/Processors/FieldReferenceComparator.cs
- Assets/Mirage/Weaver/Processors/FieldReferenceComparator.cs.meta
- Assets/Mirage/Weaver/Processors/PropertySiteProcessor.cs
We load and store field references,  so use that.
> refactor: load and stores use field references

- Assets/Mirage/Runtime/LogFactory.cs
- Assets/Tests/Editor/LogFactoryTests.cs
when using `LogError(null, msg)` it uses the first arg as a tag for the message like `tag: msg`, but if the tag is null is still adds the colon leading the the log being `: msg`
> fix: stopping `: ` being at the start of all log messages

- Assets/Mirage/Weaver/Readers.cs
When passing a NetworkBehavior derived class as a parameter, we were generating
invalid IL.  Mono was ok with it, but it caused a problem for IL2PP.
With this change,  we will include the proper class cast instruction
fixes #629
> fix: passing NetworkBehaviors in RPC works with IL2PP

- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
Similar to #630,  related to #629
when using a network behavior in a syncvar,  for example:
```cs
[SyncVar]
public Player target;
```
We generated invalid IL that cause compilation issues with IL2PP.
Mono didn't care.
This change adds the proper class cast instructions when reading the value
from the wrapper
> fix: passing NetworkBehaviors in syncvars work with il2cpp

- Assets/Mirage/Runtime/PlayerSpawner.cs
- Assets/Tests/Runtime/Host/PlayerSpawnerTest.cs
- Assets/Tests/Runtime/Host/PlayerSpawnerTest.cs.meta
> feat: add more control over player spawning

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/IClientObjectManager.cs
- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs
This object layer ref should not exist on the NetworkClient. This is a breaking change.
> refactor: move LocalPlayer to ClientObjectManager

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
When launching the welcome window in my project, the tab was visible. This PR will remove it since it is useless.
> fix: remove sponsor tab in welcome window

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
Currently, the welcome window tries to find the icon in Assets/Mirage. The uxml url is now changed to reference the icon from the packages folder.
> fix: welcome window icon not being found

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
File format should not be included in the resource
before:
after:
> fix: mirage icon missing in welcome window

- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Samples~/Pong/Scripts/PaddleSpawner.cs
- Assets/Tests/Performance/Runtime/HeadlessBenchmark/Scripts/HeadlessBenchmark.cs
- Assets/Tests/Runtime/ClientServer/NetworkServerTests.cs
BREAKING CHANGE: Use NetworkServer.NumberOfPlayers instead of NetworkServer.NumPlayers
> style: renaming NumPlayers to NumberOfPlayers

- Assets/Mirage/Components/NetworkProximityChecker.cs
Saw this behavior while testing the Additive Scenes sample.
The proximity checks never seem to fire because the InvokeRepeating(RebuildObservers) is added in an OnStartServer listener which its self is added on Start() which appears to be called after OnStartServer.
Other OnStartServer.AddListener calls appear to be in Awake and applying the same here appears to resolve the issue.
> fix: networkproximitychecker not invoking rebuildobservers

- doc/templates/partials/head.tmpl.partial
With this change we can now easily add mermaid diagrams to documentation.
Add a diagram like this:
```html
<div class="mermaid">
graph TD
A[Client] --> B[Load Balancer]
B --> C[Server1]
B --> D[Server2]
</div>
```
This generates the corresponding svg for that diagram.
You an use the [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor)
for easy diagram composition and examples.
> docs: support mermaid diagrams

- .github/workflows/main.yml
This is unnecessary and it does nothing,  I can create a manual license request from unity-runner and import the license here.
> ci: remove license activation request

- doc/toc.yml
Removes "Sponsor Us!" link which is unrelated to Mirage.
> docs: remove sponsor link

- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
- Assets/Tests/Runtime/Host/HostSetup.cs
- Assets/Tests/Runtime/Host/PlayerSpawnerTest.cs
ServerObjectManager.SpawnObjects now throw InvalidOperationException is server is not set or is not active
BREAKING CHANGE: SpawnObjects throws Exception instead of returning false
> refactor: spawnobjects throws exception instead of returning false

- Assets/Mirage/Runtime/NetworkSceneManager.cs
- Assets/Tests/Runtime/ClientServer/NetworkSceneManagerTests.cs
- Assets/Tests/Runtime/Host/NetworkSceneManagerTests.cs
BREAKING CHANGE: Use NetworkSceneManager.ActiveScenePath instead of NetworkSceneManager.NetworkScenePath
> style: renaming NetworkScenePath to ActiveScenePath

- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
adding UNITY_2020_1_OR_NEWER before opening welcome window because UIElements gives errors in ealier versions
> fix: disabling welcome window before unity 2020.1

- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/UNetwork.cs
BREAKING CHANGE: Version.Current now returns Mirage's assembly version
> refactor: replacing version enum with assembly version

- Assets/Mirage/Runtime/NetworkServer.cs
when Listening is false the transport will never call the TransportStarted function so NetworkServer will never set Active or call Started.
> fix: invoking started event when Listening is false

- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkConnection.cs
- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkConnection.cs
- Assets/Mirage/Weaver/Processors/ReaderWriterProcessor.cs
- all uses of send use forget
- no use case for wait to see if message was sent
BREAKING CHANGE: NetworkConnection.SendAsync has been removed
requires:
> refactor: removing sendasync from networkconnection

- Assets/Mirage/Runtime/Compression.cs
- Assets/Tests/Editor/Compression.cs
compressing (0,90, 0) and decompressing it gave (0,-90,0) because the encoding overflowed that the 10 bit space.
Tx to Punfish who reported it.
> fix: compression of 90 degrees angle

- Assets/Mirage/Authenticators/BasicAuthenticator.cs
- Assets/Mirage/Authenticators/TimeoutAuthenticator.cs
- Assets/Mirage/Runtime/INetworkPlayer.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkPlayer.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- disconnect just passthrough to connection.
- new concept: players can no longer be disconnected, but their connection can be
requires: 
BREAKING CHANGE: Disconnect replaced with Connection.Disconnect
> refactor: removing disconnect method from player

- Assets/Mirage/Editor/NetworkInformationPreview.cs
- Assets/Mirage/Runtime/INetworkPlayer.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- address just passthrough to connection.
- new concept: players can no longer has an address, but their connection does
requires: 
BREAKING CHANGE: Address replaced with Connection.GetEndPointAddress
> refactor: removing address property from player

- Assets/Mirage/Runtime/Compression.cs
- Assets/Tests/Editor/Compression.cs
if you compress a quaternion with zeroes,  for example, Quaternion.Euler(0,90,0),  then zeros are decompressed as zero instead of an approximation
> feat: 0 is not lossy when compressing quaternions

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/NetworkVisibility.cs
- Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
- Assets/Tests/Runtime/NetworkIdentityCallbackTests.cs
The NetworkVisibility disabled the renderers in host mode.
This is just a hack and it is unnecesary.
With this patch,  host mode just sees all objects.
If the user wants to limit how much the host player sees,
they can do it just as easily by changing the far clipping plane in the camera,
or by using unity's LOD component https://docs.unity3d.com/Manual/LevelOfDetail.html
or implementing whatever logic they want with layers.
BREAKING CHANGE: NetworkVisibility no longer disables renderers in host mode
> refactor: remove local visibility hacks

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/RemoteCallHelper.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Runtime/UNetwork.cs
Move this enum to RemoteCalls helper and renamed to RpcInvokeType
> refactor: move MirageInvokeType out of UNetwork

- Assets/Mirage/Weaver/Processors/RpcProcessor.cs
- Assets/Mirage/Weaver/Processors/ServerRpcProcessor.cs
- Assets/Tests/Runtime/Host/HostComponentTests.cs
When calling a server rpc on server mode (whether host or not),  there is no need to go through the network.  Simply invoke the user code.
This changes behaviour a little.  When you call a ServerRpc,  it now executes immediately.  Before,  it executed on the next frame. 
This also allows the ServerRpc to be invoked from the server
BREAKING CHANGE: ServerRpc execute synchronous in host mode
> perf: serverrpc bypasses network on host mode

- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Weaver/Processors/ClientRpcProcessor.cs
- Assets/Mirage/Weaver/Processors/ServerRpcProcessor.cs
client rpcs just bypass the network and get called immediately in host mode
this is the 10K example before in host mode:
This is the 10K example after in host mode:
BREAKING CHANGE: ClientRpc get called synchronously in host mode
> perf: clientrpc in host mode bypasses network

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Weaver/Processors/ClientRpcProcessor.cs
- Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
- Assets/Tests/Runtime/ClientServer/ClientServerComponentTests.cs
- Assets/Tests/Runtime/Host/HostComponentTests.cs
- Assets/Tests/Runtime/Host/NetworkBehaviourTests.cs
- doc/Articles/Guides/MirrorMigration.md
this property is only used to send message to the server, there are alternative ways to send message to the server
todo
BREAKING CHANGE: Removed ConnectionToServer property
> refactor: removing connection to server

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/GameObjectSyncvar.cs
- Assets/Mirage/Runtime/IObjectLocator.cs
- Assets/Mirage/Runtime/NetworkBehaviorSyncvar.cs
- Assets/Mirage/Runtime/NetworkIdentitySyncvar.cs
- Assets/Mirage/Runtime/Serialization/NetworkReader.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
It would be better to return bool if not found to avoid doing null check
BREAKING CHANGE: ObjectLocator now has TryGet method instead of indexer that returns null
> refactor: changing indexer to try get

- Assets/Mirage/Runtime/ServerObjectManager.cs
if id wraps it will cause problems. max value should never be reached but throw incase it does rather than wrapping silently
alternative to https://github.com/MirageNet/Mirage/pull/711
> refactor: adding checked to GetNextNetworkId

- Assets/Mirage/Runtime/ServerObjectManager.cs
keep ids small if server is stoped and started
> refactor: resetting Id on stop server

- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/NetworkTime.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
BREAKING CHANGE: fields and parameters using NetworkClient are now using INetworkClient Instead
> refactor: using interface instead of network client

- Assets/Mirage/Weaver/Processors/SyncObjectProcessor.cs
> fix: make sure resolved typedef isn't null

- Assets/Tests/Common/AsyncUtil.cs
this came up when trying to write a test that depends on the client being disconnected after failing to connect. That process takes longer than the allowed 2 seconds.
> feat: configurable wait time for tests

- Assets/Mirage/Runtime/NetworkServer.cs
fixes: #680
fixes: #681 
Also allows Listening to be toggled at runtime. Verified via Tanks example by starting with Listening=false as hostmode in editor. Then trying to connect with a client. It never connects. Then setting Listening=true. The client can now connect. Setting Listening=false again. No one was disconnect while the game went on. Opening a second standalone client it was unable to connect as expected.
> feat: not listening can now be toggled at runtime. fixes host spawning

- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Runtime/SyncVarSender.cs
- Assets/Mirage/Runtime/SyncVarSender.cs.meta
- Assets/Tests/Performance/Runtime/MultipleClients/MultipleClients.cs
- Assets/Tests/Performance/Runtime/NetworkWriter/NetworkIdentityPerformance.cs
- Assets/Tests/Performance/Runtime/NetworkWriter/NetworkIdentityPerformanceWithMultipleBehaviour.cs
BREAKING CHANGE: Dirty object collection is now inside SyncVarSender
> refactor: moving syncvar sending to its own class

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/IClientObjectManager.cs
- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/NetworkTime.cs
- Assets/Mirage/Runtime/NetworkWorld.cs
- Assets/Mirage/Runtime/NetworkWorld.cs.meta
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs
- Assets/Tests/Common/AsyncUtil.cs
- Assets/Tests/Editor/NetworkWorldTests.cs
- Assets/Tests/Editor/NetworkWorldTests.cs.meta
- Assets/Tests/Runtime/ClientServer/ClientServerComponentTests.cs
- Assets/Tests/Runtime/ClientServer/GameObjectSyncvarTest.cs
- Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviorSyncvarTest.cs
- Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourSyncvarDeeperTest.cs
- Assets/Tests/Runtime/ClientServer/GenericNetworkBehaviourSyncvarNoMiddleTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkBehaviorSyncvarTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkIdentitySyncvarTest.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
- Assets/Tests/Runtime/Host/ClientObjectManagerTest.cs
- Assets/Tests/Runtime/Host/ServerObjectManagerTest.cs
Will be split into smaller PR before merging
resolves: https://github.com/MirageNet/Mirage/issues/713
requires:
BREAKING CHANGE: NetworkIdentity collection is now found in NetworkWorld
> refactor: creating network world that will have the list of spawned objects

- Assets/Mirage/Editor/NetworkScenePostProcess.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
fixes: #609 
BREAKING: Mirage will no longer set Scene Objects to disabled as part of NetworkScenePostProcessing (this happens when you save in editor or change scene at runtime)
From comments:
I did a test solution comparing the current vs not doing the disable/enable with NetworkScenePostProcess and ServerObjectManager.
I used the ChangeScene example. In Room1 and Room2 I added 1000 SceneObjects. I ran the server in server only mode. I put a Stopwatch at the start and end of SpawnObjects().
Current: 24-26ms scene changes
Dont Disable: 17-19ms scene changes
roughly 30% faster
> refactor: mirage will no longer set scene objects to disabled

- Assets/Mirage/Runtime/Events/AddLateEvent.cs
- Assets/Mirage/Runtime/Events/AddLateEventBase.cs
- Assets/Mirage/Runtime/Events/IAddLateEvent.cs
- Assets/Tests/Editor/AddLateEventTests.cs
BREAKING CHANGE: AddLateEvent Reset no longer removes listeners
> feat: adding RemoveListener and RemoveAllListeners to AddLateEvent

- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/Host/HostSetup.cs
public event now uses IAddLateEvent, this should not effect how existing events are added via code.
BREAKING CHANGE:
- Server.Started event is now type of IAddLateEvent
- Server.Stoped event is now type of IAddLateEvent
- Server.OnStartHost event is now type of IAddLateEvent
- Server.OnStopHost event is now type of IAddLateEvent
- inspector values for changed events will need to be re-assigned
> fix: using AddLateEvent to stop race condition for server events

- Assets/Mirage/Runtime/Events/BoolAddLateEvent.cs
- Assets/Mirage/Runtime/Events/BoolAddLateEvent.cs.meta
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
- doc/Articles/Guides/GameObjects/Lifecycle.md
- doc/Articles/Guides/MirrorMigration.md
requires: https://github.com/MirageNet/Mirage/pull/766
BREAKING CHANGE:
- Identity.OnStartAuthority and IdentityOnStopAuthority are now Identity.OnAuthorityChanged and are type of IAddLateEvent<bool>
> fix: using add late event for authority and combining start and stop events

- Assets/Mirage/Runtime/Events/NetworkPlayerAddLateEvent.cs
- Assets/Mirage/Runtime/Events/NetworkPlayerAddLateEvent.cs.meta
- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
requires: https://github.com/MirageNet/Mirage/pull/764
public event now uses IAddLateEvent, this should not effect how existing events are added via code.
BREAKING CHANGE:
- NetworkClient.Connected event is now type of IAddLateEvent
- NetworkClient.Authenticated event is now type of IAddLateEvent
- NetworkClient.Disconnected event is now type of IAddLateEvent
- NetworkConnectionEvent renamed to NetworkPlayerEvent
> fix: using AddLateEvent to stop race condition for client events 

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkPlayer.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/ClientServer/NetworkServerTests.cs
- Assets/Tests/Runtime/Host/NetworkClientTest.cs
- Assets/Tests/Runtime/Host/ServerObjectManagerTest.cs
mirage should have full control over networkplayer
BREAKING CHANGE: it is no longer possible to create custom INetworkPlayer to be used inside mirage
> refactor: removing GetNewPlayer and sealing networkplayer

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/IClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Samples~/Tanks/Scripts/TankGameManager.cs
- doc/Articles/Guides/MirrorMigration.md
There was multiple ways of getting the same information and while that can be useful it can also be confusing to new users. It also provides opportunities that some values may not be set at all or in the correct order. Do you think the reduction in API redundancy and size is a good thing?
BREAKING
Old: ClientObjectManager.LocalPlayer
New: Client.Player.Identity    (note: this worked before the change too)
> refactor: remove duplicated ref to player can be accessed from client

- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
In the past ReplaceCharacter was virtual so it's functionality could be changed. That has not been the case for a while so the actual logic being in another internal call is not adding value.
> refactor: remove internal method as replace is no longer virtual

- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Tests/Performance/Runtime/MultipleClients/MultipleClients.cs
- Assets/Tests/Runtime/ClientServer/ClientServerSetup.cs
- Assets/Tests/Runtime/ClientServer/NetworkServerTests.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
- Assets/Tests/Runtime/Host/HostComponentTests.cs
- Assets/Tests/Runtime/Host/NetworkManagerTest.cs
- Assets/Tests/Runtime/Host/ServerObjectManagerTest.cs
- Assets/Tests/Runtime/NetworkIdentityCallbackTests.cs
Disconnect is not an intuitive name for a method that stops or closes the server.
BREAKING CHANGE: NetworkServer.Disconnect is now called Stop
> refactor: renaming network server disconnect to stop

- .github/workflows/main.yml
For some reason, **apt install** isn't able to fetch the correct version, thus returning a 404 error and breaking the whole CI flow, so we force it now to make sure it is an available version
> chore: fix ci to force sonar dependency version

- Assets/Mirage/Runtime/NetworkManagerGUI.cs
- Assets/Mirage/Runtime/NetworkManagerGUI.cs.meta
- Assets/Mirage/Runtime/NetworkManagerHud.cs
This PR adds an optional IMGUI menu for network manager hud, just like the one from before but with some added features. It now supports scaling and setting an anchor. 
Why? Because I can never bother with setting up a crappy UI with uGUI just to connect and I always end up making a script that auto connects for me, but it would obviously be handier to have more control. Also as someone who prototypes a lot and usually waits a really long time to make UI, this will make it so much easier to connect to servers.
> feat: add optional imgui support to network manager hud

- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
- using GetNetworkIdentity method instead of GetComponent+throw
- adding ReplaceCharacter that takes a NetworkIdentity
- adding Spawn that takes a NetworkIdentity
- removing internal SpawnObject (use public methods instead)
> feat: simplifying some checks in ServerObjectManager

- Assets/Mirage/Runtime/Serialization/NetworkReader.cs
- Assets/Mirage/Runtime/Serialization/NetworkWriter.cs
- Assets/Mirage/Weaver/Readers.cs
- Assets/Mirage/Weaver/Writers.cs
- Assets/Tests/Runtime/Serializers/NetworkWriterTest.cs
- Assets/Tests/Weaver/GeneratedReaderWriterTests.cs
- Assets/Tests/Weaver/GeneratedReaderWriterTests~/CreatesForNullable.cs
nullable types can now be used in rpc, synvars and messages. They are sent as a bool and the value
> feat: adding weaver support for nullable types

- Assets/Mirage/Runtime/Serialization/NetworkReader.cs
- Assets/Mirage/Runtime/Serialization/NetworkWriter.cs
- Assets/Tests/Runtime/Serializers/NetworkWriterTest.cs
BREAKING: write uri as a string instead. (uri.ToString())
> refactor: remove uri support from networkwriter

- Assets/Mirage/Authenticators/BasicAuthenticator.cs
- Assets/Mirage/Authenticators/TimeoutAuthenticator.cs
- Assets/Mirage/Runtime/NetworkAuthenticator.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/ClientServer/NetworkAuthenticatorTest.cs
- adding Server/Client Accept/Reject method so it is no longer required to call `base.`
- fixed TimeoutAuthenticator calling wrong authenticate method
- removing internal methods, and just having virual methods instead
- adding more doc comments
- methods are now abstract in base class instead of virtual, they should always be overriden by implementaion, and there are now accept methods to call instead of `base.`
BREAKING CHANGE:
- BasicAuthenticator now uses single string field instead of 2
- Renaming methods from OnServerAuthenticate to ServerAuthenticate
- Renaming methods from OnClientAuthenticate to ClientAuthenticate
> feat: reworking network authenticator

- Assets/Mirage/Runtime/INetworkPlayer.cs
- Assets/Mirage/Runtime/NetworkAuthenticator.cs
- Assets/Mirage/Runtime/NetworkPlayer.cs
Adding an explicit way to check if a network authenticator has accepted a client. some Authenticators dont set `AuthenticationData` so without the bool it is impossible to check if a player is authenticated or not.
> feat: adding is authenticated bool to network player

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Runtime/SyncVarReceiver.cs
- Assets/Tests/Editor/NetworkIdentityCallbackTests.cs
- Assets/Tests/Runtime/SyncVarTest.cs
- Assets/Tests/Runtime/SyncVarVirtualTest.cs
- Safely was added to imply a try catch, that try catch no longer exists
> refactor: updating errors and function names

- Assets/Mirage/Runtime/CharacterSpawner.cs
- Assets/Tests/Editor/CharacterSpawnerTest.cs
This PR fixes an issue with the character spawner component not spawning the player if the network manager has been spawned in later by a bootstrapper of some kind. I'm not exactly sure why putting the register calls in Awake fixes it but it seems to work.
> fix: character spawner not spawning player in some cases

- Assets/Mirage/Runtime/SocketLayer/AckSystem.cs
- Assets/Mirage/Runtime/SocketLayer/Config.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Tests/SocketLayer/PeerTest.cs
MaxPacketSize now sets max message size including headers. and also determine size of SocketLayer buffers
BREAKING CHANGE: BufferSize and MTU replaced by MaxPacketSize
> refactor: simplifying packet size in config

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkPlayer.cs
- Assets/Mirage/Runtime/PipePeerConnection.cs
- Assets/Mirage/Runtime/SocketLayer/Connection.cs
- Assets/Mirage/Runtime/SocketLayer/ISocket.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Mirage/Runtime/SocketLayer/SocketFactory.cs
- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
- Assets/Tests/Common/Mirage.Tests.Common.asmdef
- Assets/Tests/Common/TestSocketFactory.cs
- Assets/Tests/Runtime/ClientServer/NetworkClientDisconnectTest.cs
- Assets/Tests/SocketLayer/PeerTest.cs
- Assets/Tests/SocketLayer/PeerTestAsClient.cs
- Assets/Tests/SocketLayer/PeerTestAsServer.cs
- Assets/Tests/SocketLayer/PeerTestBase.cs
- Assets/Tests/SocketLayer/PeerTestConnecting.cs
- Assets/Tests/SocketLayer/PeerTestSendReceive.cs
Peer EndPoint is now an interface that has a method to create a copy. This will allow Sockets to re-use a single endpoint inside receive and Peer will create a copy of it when a new connection is accepted
BREAKING CHANGE: Socket functions now use an interface instead of the EndPoint class, Socket Implementations should not create a custom Endpoint class for their socket.
> perf: improving how socketlayer handles endpoints

- Assets/Mirage/Runtime/NetworkVisibility.cs
simplifies create a new NetworkVisibility because only `OnCheckObserver` will need to be overriden
> feat(NetworkVisibility): adding default implementation for OnRebuildObservers

- Assets/Mirage/Runtime/Serialization/GenericTypesSerializationExtensions.cs
- Assets/Mirage/Runtime/Serialization/NetworkReader.cs
- Assets/Mirage/Runtime/Serialization/NetworkWriter.cs
- Assets/Mirage/Runtime/Serialization/Packers/QuaternionPacker.cs
methods that throw will never be inlined, so instead they can call another method that does the throwing
> perf: adding throw helper methods so that AggressiveInlining works

- Assets/Tests/Runtime/NetworkIdentityCallbackTests.cs
this makes the code easier to maintain.
> test: use existing fixtures

- doc/Articles/Guides/FAQ.md
Afaik mirror don't support custom types and we need to create custom writers and readers in it.
> I think mirror is written in place of mirage

- Assets/Mirage/Weaver/PostProcessorReflectionImporter.cs
the default mono.cecil implmentation is very slow because it AssemblyName.FullName multiple times per import
> perf(Weaver): increasing performance of reflection importer

- Assets/Mirage/Components/NetworkPingDisplay.cs
- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/NetworkBehaviour.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/NetworkWorld.cs
- Assets/Tests/Runtime/Host/NetworkBehaviourTests.cs
- Assets/Tests/Runtime/Host/NetworkClientTest.cs
- Assets/Tests/Runtime/Host/NetworkServerTest.cs
still works in host situations. another steps towards allowing multiple worlds per client/server.
> refactor: move networktime to world

- Assets/Mirage/Runtime/CustomAttributes.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVars/FoundSyncVar.cs
- Assets/Tests/Runtime/ClientServer/SyncVarInitialOnlyTest.cs
- Assets/Tests/Runtime/ClientServer/SyncVarInitialOnlyTest.cs.meta
- Assets/Tests/Weaver/SyncVarTests.cs
- Assets/Tests/Weaver/SyncVarTests~/SyncVarsValidInitialOnly.cs
allows a syncvar to only be used for spawn message, meaning it wont be sent a 2nd time if changed later on server
> feat(Syncvar): adding InitialOnly to syncvar

- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Tests/Runtime/SyncVarHookOrderTest.cs
- Assets/Tests/Runtime/SyncVarHookOrderTest.cs.meta
- Assets/Tests/Runtime/SyncVarTest.cs
resolves: #913
BREAKING CHANGE: order syncvar hooks are called is not different for initial spawn
> refactor: setting all syncvars before calling hooks for initial spawn

- Assets/Mirage/Runtime/SocketLayer/AckSystem.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_BufferSize.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_BufferSize.cs.meta
stops send buffer getting too large (holding too many packets in memory at once)
*needs testing*
> feat(Peer): adding send buffer limit

- Assets/Mirage/Weaver/Processors/AttributeProcessor.cs
previous error says it is called on client, but that is not what happens. It is instead called when server is not active
> fix: fixing errror meessage for server client attributes

- Assets/Mirage/Runtime/MessageHandler.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Tests/Runtime/ClientServer/NetworkIdentityMessageTest.cs
- Assets/Tests/Runtime/ClientServer/NetworkIdentityMessageTest.cs.meta
- Assets/Tests/Runtime/Serialization/MessageHandlerTest.cs
adding objectLocator to object locator so that it can be used to find objects when reading network messages
> fix: fixing use of network identity in network message

- Assets/Mirage/Weaver/Processors/ServerRpcProcessor.cs
- Assets/Tests/Runtime/ClientServer/ClientServerComponentTests.cs
- Assets/Tests/Runtime/Host/HostComponentTests.cs
- Assets/Tests/Runtime/MockComponent.cs
called on serverOnly:
- Invoked directly
- Sender will be null
called on Host:
- Invoked directly
- Sender will be Server.LocalPlayer
called on Client:
- Invoked remotely
- Sender will Player that sent it
> fix(ServerRpc): fixing sender for server rpc in host mode

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/IServerObjectManager.cs
- Assets/Mirage/Runtime/Messages.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
- Assets/Tests/Runtime/Host/NetworkIdentityTests.cs
fixes: #883
BREAKING CHANGE: RemovePlayerForConnection removed, use RemoveCharacter or DestroyCharacter instead
> (DONT SQUASH) fix: adding method to remove character without destroying the object

- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Tests/Runtime/Host/NetworkIdentityTests.cs
Leftover static event from Mirror. It is unlikely anyone uses this event. If they do we can always add it back in a more appropriate place
BREAKING CHANGE: NetworkIdentity.clientAuthorityCallback removed
> refactor(NetworkIdentity): removing clientAuthorityCallback

- .github/workflows/docs.yml
the https://github.com/MirageNet/Mirage/pull/907 commit did not fix the issue, just hide the warnings
this PR should fix the issue
We will also need this fit in the main workflow when we update that because sonar also uses the csproj files
> chore: fixing doc refs in 2020.3

- Assets/Mirage/Weaver/Processors/AttributeProcessor.cs
- Assets/Tests/Weaver/ClientServerAttributeTests.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourClientOnAwake.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourClientOnAwakeWithParameters.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourHasAuthorityOnAwake.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourHasAuthorityOnAwakeWithParameters.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourLocalPlayerOnAwake.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourLocalPlayerOnAwakeWithParameters.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourServerOnAwake.cs
- Assets/Tests/Weaver/ClientServerAttributeTests~/NetworkBehaviourServerOnAwakeWithParameters.cs
This PR makes the weaver give an error when Server, Client, HasAuthority, and LocalPlayer are put on Awake.
It also includes tests that check for errors when an attribute has been placed on Awake and also that it doesn't error when you have an Awake method with parameters. 
Fixes #984
> fix: weaver error on guard attributes put on awake

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/Messages.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
Not all objects need their transform values synced when they are spawned.
And many object have it sent twice because the values will also be sent by NT.
This adds the option to disable syncing position for some Identities by disabling the option in the inspector. The values default to true so this will not break any existing projects.
This also makes the values in spawn message nullable so they will take up 3 bits extra when they are all synced. But this should not increase the otherall size because writing the payload will padd to the nearest byte. and there are already 2 bools in this struct
> perf: making transform values option to send with spawn message

- Assets/Mirage/Weaver/Processors/ServerRpcProcessor.cs
making Skeleton method static and adding the behaviour as the first arg.
Previously method was an instance method, and `behaviour` was assumed to be first arg, this seemed to work in older versions of unity but has broken in 2021.2 when the method has a return value
fixes: #997
> fix: fixing rpc return values for unity 2021.2

- Assets/Mirage/Runtime/NetworkServer.cs
This PR fixes some wording and formatting with the Debug logs. We had a mix of things like `Debug.Log("blah: " + blah2)` and `Debug.Log($"blah {blah2}")` and this was sticking out to me a bit.
This is chicken feed in the grand scheme of things, but it's a little bit of polish.
> fix: fix a typo with NetworkServer disconnection logs, improve comments, fix formatting

- Assets/Mirage/Runtime/NetworkBehaviour.cs
Current implementation of NetworkBehaviour (NB) looks for its NetworkIdentity (NI) in parent objects only if the host GameObject is active in hierarchy. If the parent is disabled, however, NB will look for NI only on the same GameObject. This behaviour is inconsistent and can be misleading.
In current codebase, this behaviour is reasoned by the fact that `GetComponentInParent()` does not support inactive GameObjects; `GetComponentsInParent()` does support them, but results in runtime memory allocations. However, [starting from Unity 2020.1](https://docs.unity3d.com/ScriptReference/GameObject.GetComponentInParent.html), `GetComponentInParent()` allows to set `includeInactive` parameter. In older Unity versions, runtime allocations can be prevented by passing a pre-allocated List to …
> fix(NetworkBehaviour): make NetworkBehaviour always look for NetworkIdentity in parents

- Assets/Mirage/Runtime/CustomAttributes.cs
- Assets/Mirage/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirage/Weaver/Processors/SyncVars/FoundSyncVar.cs
- Assets/Mirage/Weaver/Processors/SyncVars/HookMethodFinder.cs
- Assets/Tests/Runtime/ClientServer/SyncVarFireHookOnServerTests.cs
- Assets/Tests/Runtime/ClientServer/SyncVarFireHookOnServerTests.cs.meta
- Assets/Tests/Weaver/SyncVarHookTests.cs
- Assets/Tests/Weaver/SyncVarHookTests~/SyncVarHookServer.cs
- Assets/Tests/Weaver/SyncVarHookTests~/SyncVarHookServerError.cs
- doc/Articles/Guides/Sync/SyncVars.md
Can now fire hooks also on server. Requires new attribute parameter to be set. Default is false to now confuse or mess up projects. Example below...
```cs
using UnityEngine;
using Mirage;
public class Player : NetworkBehaviour
{
[SyncVar(hook = nameof(UpdateColor), fireOnServer = true)]
Color playerColor = Color.black;
Renderer renderer;
// Unity makes a clone of the Material every time renderer.material is used.
// Cache it here and Destroy it in OnDestroy to prevent a memory leak.
Material cachedMaterial;
void Awake()
{
renderer = GetComponent<Renderer>();
NetIdentity.OnStartServer.AddListener(OnStartServer);
}
void OnStartServer()
{
playerColor = Random.ColorHSV(0f, 1f, 1f, 1f, 0.5f, 1f);
}
void UpdateColor(Color oldColor, Color newColor)
{
// this is executed on this player for each …
```
> feat: feature fire hooks on server too

- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
will catch the error when the dll is not found and then default to the c# socket
resolves: https://github.com/MirageNet/Mirage/issues/929
resolves: https://github.com/MirageNet/Mirage/issues/950
> fix: adding try/catch for nanosocket

- Assets/Mirage/Runtime/SocketLayer/Connection.cs
- Assets/Mirage/Runtime/SocketLayer/LoggerExtensions.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Mirage/Runtime/SocketLayer/Pool.cs
Allowing peer logger to be null. if it is null then nothing will be logged
> refactor(SockerLayer): removing unity logger from peer

- Assets/Mirage/Runtime/MessageHandler.cs
- Assets/Mirage/Runtime/Serialization/MessagePacker.cs
- Assets/Tests/Runtime/MessagePackerTest.cs
- Assets/Tests/Runtime/Serialization/MessageHandlerTest.cs
Adding a IReadOnlyDictionary property instead of get function. This allows methods like TryGetValue to also be used
BREAKING CHANGE: MessagePacker.GetMessageType replaced with property
> refactor: replacing MessagePacker.GetMessageType with property

- Assets/Mirage/Editor/WelcomeWindow/Resources/Changelog.uxml
- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uss
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
There were some parsing issues with the welcome window change log, so I made some tweaks.
On 2021.2 it now looks like this (with Rich Text support)
On 2020.1.17 it looks like this now:
> fix: fixed welcome window change log parsing

- Assets/Mirage/Weaver/Processors/ClientRpcProcessor.cs
- Assets/Mirage/Weaver/Processors/ServerRpcProcessor.cs
fixing IL2CPP build when using targetRPCs.
Also note that Callvirt should be used calling interfaces.
note for future debugging: cpp output on failed build `Mirage/Temp/StagingArea/Data/il2cppOutput`
fixes:https://github.com/MirageNet/Mirage/issues/1020
> fix: fixing calls to interface for target RPCs

- Assets/Mirage/Editor/WelcomeWindow/Resources/WelcomeWindow.uxml
- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
This actually now properly displays all modules that are built off of com.miragenet. This can install / uninstall from packages tab from welcome window.
Atm there is one hiccup some old packages still being displayed. I think we need to delete the repo for them but I don't have permission to delete them.
> fix: fix welcome window packages tab displaying actual modules

- Assets/Mirage/Runtime/CharacterSpawner.cs
- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/INetworkSceneManager.cs
- Assets/Mirage/Runtime/NetworkSceneManager.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Samples~/ChangeScene/Prefabs/ServerOnlySceneObject Variant.prefab
- Assets/Tests/Runtime/ClientServer/NetworkSceneManagerNonHostTests.cs
- Assets/Tests/Runtime/Host/NetworkSceneManagerTests.cs
started events still take string, but finished events now return the loaded scene
resolves: #1026 
BREAKING CHANGE: 
- Scene finished loading events now return scene
- SceneChangeEvent class renamed to SceneChangeStartedEvent and SceneChangeFinishedEvent
> feat(NetworkSceneManager)!: return scene instead of strings from events

- Assets/Mirage/Editor/ReadOnlyDecoratorDrawer.cs
- Assets/Mirage/Editor/ReadOnlyDecoratorDrawer.cs.meta
- Assets/Mirage/Runtime/CustomAttributes.cs
- Assets/Mirage/Runtime/NetworkIdentity.cs
avoids confusion with users thinking they need to be set by them
> refactor: making networkidentity references readonly in inspector

- Assets/Mirage/Runtime/ClientStoppedReason.cs
- Assets/Mirage/Runtime/SocketLayer/Config.cs
- Assets/Mirage/Runtime/SocketLayer/ConnectKeyValidator.cs
- Assets/Mirage/Runtime/SocketLayer/Enums/RejectReason.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Tests/Runtime/ClientServer/NetworkClientDisconnectTest.cs
- Assets/Tests/SocketLayer/ConnectKeyValidatorTest.cs
- Assets/Tests/SocketLayer/PeerTestBase.cs
This will ensure that client connecting is on the same major version as the client.
This key can be overriden by setting the value in Config
BREAKING CHANGE: Mismatched server/client versions will no longer be able to connect to each other
> feat(SocketLayer)!: adding conection key based on mirage version

- Assets/Mirage/Runtime/Messages.cs
- Assets/Mirage/Runtime/RemoteCalls/ServerRpcSender.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
nullable will cause 1 bit for null, but that will be rounded up to 1 bytes when sending message.
This adds a seperate message for replyId so that it does not take up any extra bandwidth when it is not included
> perf: moving replyId to its own message

- Assets/Mirage/Runtime/Sockets/Udp/UdpSocket.cs
dont need Connect() call if using sendTo
> fix: fixing udp socket for macOS

- Assets/Mirage/Samples~/Chat/Scripts/ChatWindow.cs
When [`Player.RpcReceive`](https://github.com/MirageNet/Mirage/blob/master/Assets/Mirage/Samples%7E/Chat/Scripts/Player.cs#L22) is called, an `MissingReferenceException` is thrown and prevents sample from running properly.
The commit unsubscribes `ChatWindow` from `Player` events.
> fix: fix bug when running sample scene

- Assets/Mirage/Runtime/NetworkServer.cs
This PR fixes a minor issue where a server socket is created without regard to the listening status.
NetworkServer will also spit out a correct log entry now, that reflects what mode it is running. For example, if it's not listening it will now say "Server created, not listening for connections" instead of just saying "server started listening" which is wrong. 
Before:
- Create socket
- Internal stuff
- Are we listening? If yes, set up the peer
- Output a log message saying the server started listening... _(even if it isn't listening!)_
After:
- Internal stuff
- Are we listening? If yes, create the socket, set up peer, output a log entry saying it's now listening for connections
- Not listening? Output a message saying server created but not listening for connections
I have also added …
> fix: networkserver shouldn't create socket if we're not listening (addresses ticket #1054)

- CONTRIBUTING.md
This PR improves the contribution readme file as there was references to Mirror. These have been changed to Mirage for consistency (and we're not Mirror). It also corrects some spacing issues (ie. double or triple spaces after a full stop), and adds some clarification as to what you should put in the bug report (for example, "Arch Linux" when asked about what operating system you're using).
There are some other cosmetic things such as grammar checks and tidy ups.
> chore: improve contributing readme file

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/Serialization/NetworkWriterPool.cs
- Assets/Mirage/Runtime/SocketLayer/AckSystem.cs
- Assets/Mirage/Runtime/SocketLayer/Config.cs
- Assets/Mirage/Runtime/SocketLayer/Connection.cs
- Assets/Mirage/Runtime/SocketLayer/Peer.cs
- Assets/Mirage/Runtime/SocketLayer/SocketFactory.cs
- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
- Assets/Tests/Common/TestSocketFactory.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_BufferSize.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Fragmentation_Receive.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Fragmentation_Send.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_1stSend.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_DroppedSends.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_ManySends.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Notify_NoDroppedSends.cs
- Assets/Tests/SocketLayer/AckSystem/AckSystemTest_Reliable.cs
- Assets/Tests/SocketLayer/ByteUtilsTest.cs
- Assets/Tests/SocketLayer/PeerTest.cs
- Assets/Tests/SocketLayer/PeerTestBase.cs
- Assets/Tests/SocketLayer/PeerTestSendReceive.cs
Allows max packet size to be set by sockets rather than the general peer config.
BREAKING CHANGE: socket factories not have to override abstract MaxPacketSize property
> refactor(SocketLayer)!: moving MaxPacketSize to SocketFactory

- Assets/Mirage/Runtime/CharacterSpawner.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
This PR is mainly a slight cosmetic change inspired by Mirror. It replaces the spawned player name with the object name and the endpoint (Mirror uses a connection id, but since Mirage doesn't have that, we use the Endpoint instead). For example:
```
BEFORE:
Heroine(Clone)
AFTER:
Heroine [::ffff:192.168.88.200:38008]
```
This should help debugging.
> refactor(CharacterSpawner): nicer names on spawned characters (prefab name + endpoint) [skip ci]

- Assets/Mirage/Runtime/NetworkIdentity.cs
The aim of this PR is mainly to improve the consistency with string formatting and also improve error messages.
An example of the string formatting: 
```
BEFORE:
logger.Log("Mirage player " + player + " was kicked from the server for reason: " + reason + ". Bye bye!");
AFTER:
logger.Log($"Mirage player {player} was kicked from the server for reason: {reason}. Bye bye!");
```
The error message improvements are minor, but freshens and tidies them up, as well as make them a little friendlier so if a developer is reading the log, it seems to be suggesting "Hey, this isn't the correct call, you should call that first, then call this" rather than "Rawr! You got an exception, you did something wrong!". _Okay, maybe not that dramatic, but you get the idea._
> refactor(NetworkIdentity): consistency with string formatting and updated error messages

- Assets/Mirage/Runtime/NetworkSceneManager.cs
returning null means that unity failed to load the scene, in this case we should throw because we can't continue
resolves: https://github.com/MirageNet/Mirage/issues/1027
> fix: throwing if SceneManager returns null

- Assets/Mirage/Runtime/Serialization/CollectionExtensions.cs
- Assets/Mirage/Weaver/Serialization/Readers.cs
- Assets/Mirage/Weaver/Serialization/Writers.cs
- Assets/Mirage/Weaver/SerializeFunctionBase.cs
- Assets/Tests/Runtime/Serialization/ArraySegmentWriterTest.cs
- Assets/Tests/Runtime/Serialization/NetworkWriterTest.cs
For byte[], 0 is written for null and count+1 is written for count, we can re-use this for other collections
Splitting these methods into seperate fucntions so they can be used for all collections
Also changing are ArraySegment<T> is read, it now has its own extension methods that checks if the array is null or not before creating the segment
> perf: using plus 1 count for other collection types

- Assets/Mirage/Runtime/MessageHandler.cs
- Assets/Tests/Runtime/Serialization/MessageHandlerTest.cs
If it is a known type it is likely developer error, so we want to warn about it so it can be fixed
> fix: increasing log to warning when receiving known type without handler

- Assets/Mirage/Runtime/INetworkClient.cs
- Assets/Mirage/Runtime/INetworkServer.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
This PR stems from [this](https://discord.com/channels/809535064551456888/891063500846297161/977708825207517184) conversation. It adds the ability to start the server from the `INetworkServer` and connect from the `INetworkClient`.
Starting the host is also possible from the interfaces, however it required making several methods `public` instead of `internal` to allow for the interfaces to decouple the `NetworkServer` and `NetworkClient`. Let me know if this is ok.
> fix: adding ability to start the Client & Server from interfaces

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
peer runs on main thread, so will be paused if runInBackground is false. This causes connections to timeout.
> fix: enabling runInBackground so that connections dont timeout

- Assets/Mirage/Runtime/NetworkIdentity.cs
- Assets/Mirage/Runtime/NetworkIdentityIdGenerator.cs
using SerializedObject was causing warning whe the editor first opened
using Undo should fix this
> fix: fixing warning created from id generator

- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Tests/Runtime/ClientServer/ServerObjectManagerTests.cs
Allows AddCharacter to skip the new character if it already exists. This stops 2 spawn message being sent for same object
> feat: adding SpawnVisibleObjects method that can skip objects

- Assets/Mirage/Runtime/Sockets/Udp/NanoEndPoint.cs
- Assets/Mirage/Runtime/Sockets/Udp/NanoSocket.cs
- Assets/Mirage/Runtime/Sockets/Udp/NanoSockets/Scripts/NanoSockets.cs
- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
This is a multi-commit PR that addresses a few things:
1. Renamed some variables (ie `isWebgl` is now `isWebGL`). This is more just for cosmetic appearance, and these were used internally and not outside of the Mirage Sockets' layer.
2. Introduced NanoSockets compatibility for Mirage Standalone. Had to remove `#if UNITY_EDITOR || UNITY_STANDALONE` defines in the NanoSockets source files or the Mirage Standalone project would complain.
3. Patched `isDesktop` to point to a boolean-returning function instead of a expression for Mirage Standalone compatibility.
4. Rewrote/Reworked some tooltip(s) and error message(s).
Tested briefly on Windows instance of the Unity Editor version 2020.3.38. Shouldn't break anything, I hope.
> fix: miscellanous NanoSocket bits and pieces, add Mirage Standalone support

- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
Replaced some properties with a new platform detection function, and better support for NET Core Apps/NET 5.0 or greater (ie. Mirage Standalone).
> refactor: rework the UdpSocketFactory

- Assets/Mirage/Runtime/Sockets/Udp/Mirage.Sockets.Udp.asmdef
- Assets/Mirage/Runtime/Sockets/Udp/NanoEndPoint.cs
- Assets/Mirage/Runtime/Sockets/Udp/NanoSockets/Scripts/NanoSockets.cs
- Assets/Mirage/Runtime/Sockets/Udp/UdpSocketFactory.cs
This can probably be reverted in a later commit or PR if Unity looks into the StringBuilder SIGABRT crash and fixes their IL2CPP StringBuilder Marshalling. I've reported that bug to Unity, currently awaiting resolution. Confirmed bug with GDB debugger and help of imer and FakeByte.
What this PR features is the following:
- A fix to prevent IL2CPP SIGABRT crashes when calling NanoSocket's Address.ToString() function. Tested and confirmed working on Manjaro x86_64 with the Mirage Basic demo. It allocates memory however, improved version welcome!
- Adding our modification notice to the C# wrappers' header.
- Minor restructure out of pure what-if testing (don't make a new address inside a function iirc).
> fix: il2cpp linux runtime SIGABRT crash with nanosockets (unity 2021.3.15+ ?)

- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Tests/Runtime/NetworkClient.meta
- Assets/Tests/Runtime/NetworkClient/NetworkClientSendIfDisconnectedTest.cs
- Assets/Tests/Runtime/NetworkClient/NetworkClientSendIfDisconnectedTest.cs.meta
Fixes a NullReferenceException being fired since the NetworkClient's Player reference is null when trying to use the `Send(...)` function while disconnected. Discovered by myself while implementing some backend stuff in Mirage Standalone. 
Instead, throw a InvalidOperationException and explain to the user that sending things when disconnected is bad.
> fix: throw InvalidOperationException if network client attempts to send messages while disconnected

- Assets/Mirage/Runtime/Logging/EditorLogSettingsLoader.cs
- Assets/Mirage/package.json
A fresh install of Mirage on the 2023.1 alpha caused a few issues:
- Compilation issues due to ambiguous matches between UniTask's GetAwaiter and Unity's new Awaitable GetAwaiter
- Depcreation warning as Object.FindObjectOfType is now deprecated
I fixed these using the following methods:
- Update the UniTask dependency to 2.3.3 (the ambiguous match was fixed in [UniTask 2.3.2](https://github.com/Cysharp/UniTask/releases/tag/2.3.2)
- Added #if define in EditorLogSettingsLoader to use the new `Object.FindFirstObjectOfType`
I have not updated any tests to remove any warnings when in 2023.1, but I could if desired.
> fix: errors and warnings on 2023.1 alpha

- Assets/Mirage/Editor/NetworkBehaviourInspectorUIToolkit.cs
There's a really weird issue that sometimes happens where lists are not reorderable when the base type is NetworkBehavior. No clue why actually binding property fields causes this. It seems to work fine without binding when you directly assign the property to the field.
> fix: ui toolkit list fields not being reorderable

- Assets/Mirage/Components/NetworkManagerGUI.cs
The current NetworkManagerGUI that is used by Mirage is rather outdated. Buttons are hard to click on if you have a touch screen, the white text blends in with the scene, etc. Overall, it was begging for an update.
This PR introduces an almost-completely refactored NetworkManagerGUI that is using the `GUI.Window` functionality to give it a nice background and title. In the future, one could turn it into a draggable GUI Window, but for now it's more elegant but keeping things simple.
Empty space will be used in later updates (current connection count, etc).
**Screenshots**
> refactor(NetworkManagerGUI): overhaul the debug controls

- Assets/Mirage/Editor/WelcomeWindow/WelcomeWindow.cs
using FromScriptableObject doesn't work in 2022. So using PackageInfo.GetAllRegisteredPackages instead
> fix: fixing path of change log

- Assets/Mirage/Runtime/CharacterSpawner.cs
- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkSceneManager.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Runtime/SocketLayer/SocketFactory.cs
These high level classes did not have a HelpUrl pointing to Mirage documentation. The others that do exist seem to prefer using Guides > Comps > Class Ref. I tried to stick to that same priority but some are missing. I figured its better to link to a valid Mirage doc instead of letting it error off to a Missing Doc page on unity3d.com
> fix: add missing HelpUrl tag to high level classes

- doc/docs/general/getting-started.md
Install Directions should from the website are hard to find. This change puts the install directions (copied from [the mirage-quick-start-guide community guide](https://miragenet.github.io/Mirage/docs/guides/community-guides/mirage-quick-start-guide)) right after the Getting Started button on the landing page from [mirage.net](https://miragenet.github.io/Mirage/).
> docs: add install directions to getting started

- Assets/Mirage/Runtime/ClientObjectManager.cs
When registering a prefab with the below function, the resulting SpawnHandler has an empty `Prefab`.
```cs
clientObjectManager.RegisterSpawnHandler(prefab, OnClientSpawnCharacter, OnClientUnSpawnCharacter);
```
With a custom spawn handler, the below function fails even with a registered prefab.
```cs
private NetworkIdentity OnClientSpawnCharacter(SpawnMessage msg)
{
if (!msg.PrefabHash.HasValue)
return null;
int prefabHash = msg.PrefabHash.Value;
SpawnHandler handler = clientObjectManager.GetSpawnHandler(prefabHash);
NetworkIdentity prefab = handler.Prefab;
var pos = msg.SpawnValues.Position ?? prefab.transform.position;
var rot = msg.SpawnValues.Rotation ?? prefab.transform.rotation;
return Instantiate(prefab, pos, rot);
}
```
This pull request adds the below constructors for …
> fix(ClientObjectManager): add prefab to SpawnHandler when registering

- doc/docs/guides/sync/sync-var-hooks.md
Add a description of the timing of hook execution.
This small change can help people understand the timing of the hook invocation relative to the state of the local SyncVar when the hook is executing.
> refactor: Update sync-var-hooks.md with timing information

- Assets/Mirage/Runtime/NetworkClient.cs
This is a simple fix to stop the NetworkClient emitting a weird line that is "Authentication succcessful with" (where there's nothing past 'with' since `message.AuthenticatorName` is null/empty). This commit now makes it emit either a success message with the name or it was successful w/o an authenticator.
Chance of breaking existing projects? Unlikely.
Will it break existing tests? Checked and didn't see any tests checking the logging being emitted, so (safely?) assuming No.
> fix: authenicator success message wording in NetworkClient

- Assets/Mirage/Runtime/ClientObjectManager.cs
- Assets/Mirage/Runtime/NetworkClient.cs
- Assets/Mirage/Runtime/NetworkServer.cs
- Assets/Mirage/Runtime/RemoteCalls/RpcHandler.cs
- Assets/Mirage/Runtime/ServerObjectManager.cs
- Assets/Mirage/Runtime/SyncVarReceiver.cs
- Assets/Tests/Runtime/ClientServer/ClientObjectManagerTest.cs
fixes: https://github.com/MirageNet/Mirage/issues/1186
- adding pending list to avoid spawning twice
- storing incoming message for netid if spawn is spending
- applying pending message in order after async spawn is complete
- (refactor) moving SyncVarReceiver to ObjectManagers
> feat: storing message for Async spawning and applying them after
